### ISSUE TITLE
Unable to fingerprint user devices

### ISSUE THREAD

**Issue by VinnyVicious** [fingerprintjs/fingerprintjs#1002]
### Scenario

Imagine an office full of old people who don't bother to install or configure their own OS/Browser/Fonts and they only use company provided laptops, which of course are all the same, with the same Windows versions and same corporate-approved installation. They also share the same IP.

### Fingerprint data

Currently, fingerprintjs provides the same fingerprint for every user in that scenario. It should be different.

**Comment by JuroUhlar** [comment]
Thanks for the feedback! 

FingerprintJS uses a simple hashing function over the retrieved browser signals to generate the browser identifier. You can [add or remove entropy components](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) to find the right balance of false negatives and false positives that best suits your use case. This is almost always a trade-off (adding signals to reduce false positives in the circumstances you described will also lead to more false negatives generally), so we have robust criteria for adding signals to FingerprintJS. 

[Fingerprint Pro](https://fingerprint.com/github/) (the commercial version of FingerprintJS) uses more signals (including server-side information) and a more advanced, fuzzy matching algorithm, reducing false positives to 0.5%. It should be much more successful (though still not perfect) at distinguishing browsers even in more uniform environments like you described. Consider giving it a go for your use case (there is a free trial) and let us know how it goes! 

Cheers

**Comment by VinnyVicious** [comment]
I've used the Pro demo to emulate that scenario I described, and it still failed to uniquely identify users.

**Comment by VinnyVicious** [comment]
Luckily, I left age out of the scenario emulation.

**Comment by Valve** [comment]
@VinnyVicious if you want to dive into this, can you please send me an email to valentin@fingerprint.com and I'll connect you with the  right people to dive into your use case, thanks!
