### ISSUE TITLE
Wrong typing for components items

### ISSUE THREAD

**Issue by giovannetti-eric** [fingerprintjs/fingerprintjs#1042]
### Scenario

When I try to extract values from `components` properties, I get TS errors telling me that `value` properties do not exist.

```JS
import FingerprintJS from "@fingerprintjs/fingerprintjs";

const fp = await FingerprintJS.load();
const fpData = await fp.get();
const { components } = fpData;

console.log({
  languages: components?.languages.value ?? null,
  platform: components?.platform.value ?? null,
});
```

For example, I get:

`Property 'value' does not exist on type 'Component<string[][]>'.
  Property 'value' does not exist on type '{ error: unknown; } & { duration: number; }'.ts(2339)`

`Property 'value' does not exist on type 'Component<string>'.
  Property 'value' does not exist on type '{ error: unknown; } & { duration: number; }'.ts(2339)`

**Comment by Finesse** [comment]
That's because the `Component` type consists of 2 subtypes: `{ value: any, duration: number } | { error: any, duration: number }`. The `value` property exists only in 1 subtype, so TypeScripts emits the errors. To fix it, you need to first check that the `value` property exists:

```ts
console.log((components && 'value' in components.languages && components.languages.value) ?? null)
```

**Comment by Finesse** [comment]
I'm closing the issue because of the lack of response. If you want to continue the discussion, feel free to leave a comment, I'll reopen the issue.

**Comment by giovannetti-eric** [comment]
Ok, thanks for the explanation.
