### ISSUE TITLE
[Question] Can Fingerprint Identification detect user uniquely who is using kasm destroyable browser session ?  

### ISSUE THREAD

**Issue by Greatz08** [fingerprintjs/fingerprintjs#1047]
Kasm workspace give users option to create destroyable browsers sessions too like for 1,2 or more hrs and than total chromium or firefox session is deleted so can Fingerprint Identification (closed source, proprietary solution) detect those users uniquely who are using this for anonymous surfing ?

**Comment by Valve** [comment]
Hi @Greatz08 
Thanks for your question. 
We didn't test our Pro version on the Kasm workspace product, however our product has a free unlimited 14-day trial, which you can start on dashboard.fingerprint.com/signup
Please feel free to try it out and get back with your results. 
If you observe any misidentifications, such as false positive errors (two unrelated browsers having the same visitor ID) or false negative errors (one same browser has two different visitor IDs across two different sessions), please report those errors and we'll submit them to our product & engineering teams.

**Comment by Valve** [comment]
I think there will be a massive difference in the false positive rate between FingerprintJS and Fingerprint Identification.
While the false negative rate is the same, there will be a higher probability for someone else to get the same visitor ID as you had on the free version.
