### ISSUE TITLE
:-<ChatAGipt7\><fix/bugs>

### ISSUE THREAD

**Issue by Myahr208** [fingerprintjs/fingerprintjs#1061]
[

### Scenario

- What's the scenario, what happens and what did you expect to happen?
- What device and browser are you using?
- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment.)

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by makma** [comment]
Closing as spam,
