### ISSUE TITLE
Document edge cases

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#283]
From https://github.com/Valve/fingerprintjs2/pull/147#issuecomment-350654006

- Adblock may be wrong if fingerprint is computed directly after/on page load. Give the browser a few ms to load the adblock plugin (with setTimeout). (What does "a few ms" mean? Does anyone have any experience with concrete values of "a few" here?)
- Canvas FP may be different on page reload/same browser, same device due to switching between on-chip GPU and "real" GPU. Seen on Macbook Pro and maybe HP Probook 650 G2. See #147, #280, #226, #308

**Comment by Valve** [comment]
These edge cases are either handled automatically or no longer relevant for v3, which as been released. Closing.
