### ISSUE TITLE
Ignore Flash plugin by default

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#290]
See https://github.com/Valve/fingerprintjs2/issues/248#issuecomment-318680189

**Comment by jonashaag** [comment]
We should prioritise this

**Comment by GrosSacASac** [comment]
Is that not already the case ?
https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L264

**Comment by jonashaag** [comment]
No, the Flash plugin inside the `plugins` component

**Comment by Valve** [comment]
v3 will not have Flash support.

**Comment by Finesse** [comment]
Flash is removed in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0)
