### ISSUE TITLE
Different fingerprint but same values?

### ISSUE THREAD

**Issue by arya6000** [fingerprintjs/fingerprintjs#308]
I'm running iOS 11.2.6 and I noticed sometimes the fingerprint I get is wrong. after I click "Get my fingerprint" I get the correct (the usual one) For example: Initially I got this finger print

```
Fingerprintjs2
Your browser fingerprint: 
19442d4a484fe8cff1ee30ef907a8112

Time took to calculate the fingerprint: 656ms

Detailed information: 

user_agent = Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Ver
language = en-US
color_depth = 32
pixel_ratio = 2
hardware_concurrency = unknown
resolution = 568,320
available_resolution = 568,320
timezone_offset = 240
session_storage = 1
local_storage = 1
indexed_db = 1
open_database = 1
cpu_class = unknown
navigator_platform = iPhone
do_not_track = unknown
regular_plugins = 
canvas = canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAAAXNSR0IArs4c6QAADAJJREFUeAHtnU
adblock = false
has_lied_languages = false
has_lied_resolution = false
has_lied_os = false
has_lied_browser = false
touch_support = 0,true,true
js_fonts = Arial,Arial Hebrew,Arial Rounded MT Bold,Courier,Courier New,Georgia,Helvetica,Helvetica Neue,Palati
```

The day after I get it again and I get this

```
Fingerprintjs2
Your browser fingerprint:
11d69b468a63edeced917bb82a83b605

Time took to calculate the fingerprint: 511ms

Detailed information: 

user_agent = Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Ver
language = en-US
color_depth = 32
pixel_ratio = 2
hardware_concurrency = unknown
resolution = 568,320
available_resolution = 568,320
timezone_offset = 240
session_storage = 1
local_storage = 1
indexed_db = 1
open_database = 1
cpu_class = unknown
navigator_platform = iPhone
do_not_track = unknown
regular_plugins = 
canvas = canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAAAXNSR0IArs4c6QAADAJJREFUeAHtnU
adblock = false
has_lied_languages = false
has_lied_resolution = false
has_lied_os = false
has_lied_browser = false
touch_support = 0,true,true
js_fonts = Arial,Arial Hebrew,Arial Rounded MT Bold,Courier,Courier New,Georgia,Helvetica,Helvetica Neue,Palati
```

All the values are the same from the two examples above but the fingerprint is different. When I pressed "Get my fingerprint" again it generated the same old fingerprint.

**Comment by jonashaag** [comment]
Could you use this jsfiddle and paste both day's results here? https://jsfiddle.net/efer6pgy/

**Comment by arya6000** [comment]
But I can't reproduce the wrong one. It just happened randomly. Now I am getting the correct one. BTW I used https://valve.github.io/fingerprintjs2/

**Comment by beebase** [comment]
FYI . I was consistently getting a different fingerprint each time on an iPhone5. After examining the components I discovered that the canvas part changed every time I fired up my App.

"value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**Jd/atQwgJJEBMQAhBlEXAbRDBZUbQURzDGtTBGb/uoyOtM....................**

"value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**JOvvWIYQEEiAmIIQgyiLgNojgMiPoKI5hDergjF/30ZHWmXEZVBQU2UXR.....................**



Not sure why this happens. Anyway, I disabled the canvas in the fingerprint options, making my fingerprint becoming consistent again.

```
new Fingerprint2({excludeCanvas: true}).get(
        (_keyFingerPrint, components) => {
       ......
```

**Comment by jonashaag** [comment]
@beebase thanks for the report, let's move this to #323

**Comment by pdbc** [comment]
Same issue with me.  Tested with IE and Chrome, after a while the fingerprint changes but the values on which it is based are the same:

Chrome - 09/05/2018

Fingerprintjs2
Your browser fingerprint:
0a287c11f7d3521f85b48240ee25a3e1

Time took to calculate the fingerprint: 579ms

Detailed information:

Wed May 09 2018 08:46:40 GMT+0200 (Romance Daylight Time)

language = en-US
color_depth = 24
device_memory = 8
hardware_concurrency = 4
timezone_offset = -120
session_storage = 1
local_storage = 1
indexed_db = 1
open_database = 1
cpu_class = unknown
navigator_platform = Win32
canvas = canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAN/UlEQVR4Xu2dQYhkRxnHv3rds4uIaM
webgl_vendor = Google Inc.~ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
adblock = false
has_lied_languages = false
has_lied_resolution = false
has_lied_os = false
has_lied_browser = false
touch_support = 0,false,false
js_fonts = Arial,Arial Black,Arial Narrow,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambr

----------------------------
Chrome - 16/05/2018

Your browser fingerprint:
cb1a45f919e7c870bad390cdfc10b893

Time took to calculate the fingerprint: 464ms

Detailed information:

Wed May 16 2018 14:59:22 GMT+0200 (Romance Daylight Time)

language = en-US
color_depth = 24
device_memory = 8
hardware_concurrency = 4
timezone_offset = -120
session_storage = 1
local_storage = 1
indexed_db = 1
open_database = 1
cpu_class = unknown
navigator_platform = Win32
canvas = canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAN/UlEQVR4Xu2dQYhkRxnHv3rds4uIaM
webgl_vendor = Google Inc.~ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
adblock = false
has_lied_languages = false
has_lied_resolution = false
has_lied_os = false
has_lied_browser = false
touch_support = 0,false,false
js_fonts = Arial,Arial Black,Arial Narrow,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambr

**Comment by jonashaag** [comment]
Does you computer have a native graphics card and an on-chip one/

**Comment by pdbc** [comment]
No, its a regular HP laptop. Nothing too fancy.

**Comment by pdbc** [comment]
HP Probook 650 G2 (is this information sufficient)?

**Comment by jonashaag** [comment]
See also https://github.com/Valve/fingerprintjs2/issues/226#issuecomment-317877077

**Comment by pdbc** [comment]
Thanks for the info.  As I read it correct over there this issue cannot be fixed (e.g. you cannot force which graphic card to use).  Can you disable the graphic card in de equation?

**Comment by jonashaag** [comment]
Sure, just exclude webgl and canvas fingerprints.

**Comment by Finesse** [comment]
> FYI . I was consistently getting a different fingerprint each time on an iPhone5. (worked ok on Android) After examining the components I discovered that the canvas part changed every time I fired up my App.
> 
> "value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**Jd/atQwgJJEBMQAhBlEXAbRDBZUbQURzDGtTBGb/uoyOtM....................**
> 
> "value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**JOvvWIYQEEiAmIIQgyiLgNojgMiPoKI5hDergjF/30ZHWmXEZVBQU2UXR.....................**
> 
> Not sure why this happens. Anyway, I disabled the canvas in the fingerprint options, making my fingerprint becoming consistent again.
> 
> ```
> new Fingerprint2({excludeCanvas: true}).get(
>         (_keyFingerPrint, components) => {
>        ......
> ```

@beebase Could you please post the full canvas strings so that I can see the pictures and find what's different?

**Comment by beebase** [comment]
@Finesse I'm sorry, I don't have access to that code anymore 😞

**Comment by Finesse** [comment]
- I see no signal differences in [the arya6000's comment](https://github.com/fingerprintjs/fingerprintjs/issues/308#issue-306190375)
- There are 2 differences in the [ssitdikov's comment](https://github.com/fingerprintjs/fingerprintjs/issues/308#issuecomment-381535067): `adblock` and `plugins`. The AdBlock issue has been solved. Flash is removed in Chrome 88, and I can reproduce neither in Chrome 65 on Windows and macOS, nor in Chrome 88 on Windows, macOS and Ubuntu. Feel free to reopen if you have additional details.
- The [beebase's](https://github.com/fingerprintjs/fingerprintjs/issues/308#issuecomment-389450618) issue is moved to #323.
