### ISSUE TITLE
difer on cross_browser jsFont results 

### ISSUE THREAD

**Issue by LeorPoirot** [fingerprintjs/fingerprintjs#314]
I feel confused why the js_font on different broswer is different from each other:
for Microsoft Edge js_fonts = Arial,Arial Black,Arial Narrow,Arial Rounded MT Bold,Book Antiqua,Bookman Old Style,Calibri,Cambria

for IE js_fonts = Arial,Arial Black,Arial Narrow,Arial Rounded MT Bold,Book Antiqua,Bookman Old Style,Calibri,Cambria (the same as above)

for Chrome js_fonts = Arial,Arial Black,Arial Narrow,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambria Math,Century,C(two more fonts at the end)
 
My OS is windows 10

Thank you !

**Comment by jonashaag** [comment]
Not sure, maybe different font implementations. Someone should do some extensive cross-browser font testing at some point.

**Comment by Kogmawzy** [comment]
Anyway,thanks a lot ,maybe I can do some testing

**Comment by Finesse** [comment]
The fonts component is browser dependent. This is expected behavior. Similar issues: https://github.com/fingerprintjs/fingerprintjs/issues/441, https://github.com/fingerprintjs/fingerprintjs/issues/528.
