### ISSUE TITLE
Changing canvas fingerprint on iPhone 5

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#323]
From @beebase in #308

FYI . I was consistently getting a different fingerprint each time on an iPhone5. (worked ok on Android)  After examining the components I discovered that the canvas part changed every time I fired up my App.

```
"value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**Jd/atQwgJJEBMQAhBlEXAbRDBZUbQURzDGtTBGb/uoyOtM....................**
```

```
"value": "canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAAXNSR0IArs4c6QAAQABJREFUeAHs3XmcXFWd//9PVe9**JOvvWIYQEEiAmIIQgyiLgNojgMiPoKI5hDergjF/30ZHWmXEZVBQU2UXR.....................**
```

Not sure why this happens. Anyway, I disabled the canvas in the fingerprint options, making my fingerprint becoming consistent again.

```
new Fingerprint2({excludeCanvas: true}).get(
        (_keyFingerPrint, components) => {
       ......
```

**Comment by Finesse** [comment]
@jonashaag Hi, I'm a new (co)maintainer of this project. I don't know canvas deeply too, but I have an idea. What if the algorithm runs the canvas check twice in a row and if the results differ then discards the canvas part? Same for [WebGL](https://github.com/fingerprintjs/fingerprintjs2/issues/310). I haven't tried it, just wanna know if you have.

**Comment by Valve** [comment]
@Finesse that may work, but what can also happen is that if you run it two times in a row, they will be the same, but if you run them again in the future (say in several minutes), they can be different.
I can also suggest rotating the image and after that exporting the canvas to base64.
Please try to reproduce it in our browserstack account. If you cannot, mark as need more details and `unable to reproduce`.

**Comment by Finesse** [comment]
@Valve Is solving this issue required for v3?

**Comment by Valve** [comment]
@Valve not strictly. Let's work on v3 independently from this. If we get more details and are able to reproduce this, we'll fix this later.

**Comment by Finesse** [comment]
We need to know the difference between canvas pictures. Please, post full content of `canvas`/`data` of different fingerprints. Fingerprint data is available either at https://jlryy.csb.app/ (v2) or https://fingerprintjs.github.io/fingerprintjs (v3).

**Comment by Finesse** [comment]
I can't reproduce and have not enough information to debug. If you're able to reproduce it, please share the different fingerprints (see https://github.com/fingerprintjs/fingerprintjs/issues/323#issuecomment-726559310).
