### ISSUE TITLE
The fonts component gives different results

### ISSUE THREAD

**Issue by LesterDong** [fingerprintjs/fingerprintjs#366]
hi, i test firefox fp on the demo website(https://valve.github.io/fingerprintjs2/), when i first get the fp, the value is "c47be56e91cdb14ae31367c66851e4f3", then i open another tab, the value changed to "9af57a294ebb17e521c91c8a8a61fa4c", i compared component and found some difference on the component of "js_fonts", the former was "js_fonts = Arial,Arial Black,Arial Narrow,Arial Rounded MT Bold,Arial Unicode MS,Book Antiqua,Bookman Old Style", and the latter was "js_fonts = Arial,Arial Rounded MT Bold,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambria "， i want to know how to exclude font detection completely? I tried "extendedJsFonts: true" but it did not worked. This just happened on firefox , other browser worked fine.

**Comment by SleepProgger** [comment]
To disable both the flash and the javascript font detection use the options:
`{excludeFlashFonts: true, excludeJsFonts: true}`

**Comment by jonashaag** [comment]
What's your FF version, OS, and can you reproduce this?

**Comment by LesterDong** [comment]
I tried and it worked, thanks!

**Comment by LesterDong** [comment]
@SleepProgger I tried and it worked, thanks!

**Comment by LesterDong** [comment]
@jonashaag I will give you a detailed description next Monday，the laptop now is in my company.

**Comment by jonashaag** [comment]
Yeah font detection isn't 100% deterministic and reliable. If you can reproduce this that'd be great so we can improve the detection.

**Comment by Magiweb** [comment]
I can confirm I'm getting the same results in Firefox. Simply opening a new tab and visiting https://valve.github.io/fingerprintjs2/, I sometimes get the same signature, but often get different ones. When comparing the data, the fonts (or perhaps the order of the fonts?) appears to be the issue - each time the hash changes it's the js_fonts that differ. For example: 

https://screenshots.firefox.com/ByUmH0vQMXyyxntC/valve.github.io
vs
https://screenshots.firefox.com/Vh1JFmY4kkXB9aep/valve.github.io

Same browser (Firefox 62.0.3 64bit) - just opening the test page on different tabs

On Chrome I do not see this issue at all; it may be worthwhile to disable js_fonts at least in the case of Firefox. Haven't tested on other browsers / OS's.

**Comment by klingo** [comment]
I noticed a similar(?) issue with Google Chrome (Version 69.0.3497.81) and Fingerprint2 v2.0.0.

When I hard reload the browser (or clear browser cache), I always get 47 fonts.
When I normal reload the browser, I get 48 fonts (+Calibri).

**Comment by GrosSacASac** [comment]
@Magiweb try https://valve.github.io/fingerprintjs2/
same as running index.html in gh-pages branch

**Comment by Magiweb** [comment]
@GrosSacASac yep I did that and pointed that out in my original comment: https://screencast.com/t/e939xgjO8dIs

**Comment by GrosSacASac** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=732096

**Comment by GrosSacASac** [comment]
It might be a good idea to disable fonts by default, now that most UA start to implement fuzzy anti fingerprinting features

**Comment by Magiweb** [comment]
@GrosSacASac yep agree - Safari's also making it harder to identify fonts etc. (making them less "unique" by standardising the response to default fonts found on any browser). Which is why I suggested in my comment that it's probably best to not use fonts for the hash.

**Comment by GrosSacASac** [comment]
Yes and hashing everything by default is also being deprecated, I think calculating a proximity score is a better approach.

**Comment by Magiweb** [comment]
Totally agree! Also adding "weight" to specific measurements could be useful so one metric may contribute more heavily than another to the overall score.

Is that something that's in the works for fingerprintjs?

**Comment by GrosSacASac** [comment]
That is something I am thinking about, but it is a huge task, which requires a lot of thoughts and manual testing

**Comment by Magiweb** [comment]
Javascript isn't my strongest code language, but can scratch around and done a fair amount of work with statistics etc. so if I can be helpful let me know.

**Comment by Magiweb** [comment]
@jonashaag if you want to discuss / elaborate on this maybe we should create a separate topic so this topic remains relevant to the subject? 

For example, booting 100's of OS's isn't hard outside of licensing issues, particularly with Mac. The problem is how to automatically drive them inside of their UI environment since we can't use headless browsers (for obvious reasons). Also, such an infrastructure would definitely incur cost. But I'm pretty strong on the cloud / SysOps side so that's definitely something we can discuss further and try to iron out.

**Comment by jonashaag** [comment]
Yes please

**Comment by Finesse** [comment]
Is it reproducible in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0)?

**Comment by Finesse** [comment]
I can reproduce it with v2 in Firefox 62 on Windows 7 and Windows 10 on Browserstack. Meanwhile the bug isn't presented on [the v3 demo page](http://fingerprintjs.github.io/fingerprintjs/). Version 2 is outdated, please [update](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md) to v3.

I can't reproduce it with v2 in Firefox 82 on Windows 10.

The difference between the fingerprints is that `Arial Black` is absent in the second tab.
