### ISSUE TITLE
EnhancedTracking prevention in IOS12 and MacOS Mojave

### ISSUE THREAD

**Issue by magizh-okta** [fingerprintjs/fingerprintjs#371]
With EnhancedTracking prevention in IOS12 and MacOS Mojave  - **Is there any known issue or should we be worried websites getting blocked when using fingerprintjs2 ?**

https://www.apple.com/macos/mojave-preview/

When you browse the web, the characteristics of your device can be used by advertisers to create a “fingerprint” to track you. Safari now thwarts this by only sharing a simplified system profile. And now improved Intelligent Tracking Prevention keeps social media Like buttons, Share buttons, or comment widgets from tracking you without your permission. We know you’ll like that.

PS: Apologies if this is not a real issue but just wanted to check if there are any good practices for tracking or any known issues.

**Comment by mndominguez** [comment]
I have this version of macOS running currently. @jonashaag if you want and can point me in the right direction, I could help you test this.

**Comment by magizh-okta** [comment]
I tested this on safari technology preview and fingerprint computation works fine.  http://valve.github.io/fingerprintjs2/

I dont think fingerprinting would be affected  https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/

**Comment by jwest75674** [comment]
Hello,

I was about to open a new bug report, when I noticed this and wanted to share some data which indicates that Apple tracking prevention may be impacting fingerprinting from working as expected going back at least a few weeks, maybe more.





### Scenario
I am leveraging Fingerprintjs2 to gather data from many websites into a single location. As a part of my data capture, I am also sending data to Google Analytics to more easily understand the data at a glance.

I've setup each of the "hasLied" items to send a unique event to Google Analytics, so I can tally up some stats to make a report. 

As part of the reporting, I wanted to show the number of "hasLied" events (resolutions, os, language, etc.) which had been captured as true. I believe I may have accidentally stumbled onto evidence that apple is indeed impacting fingerprintjs2.

Also this is worth sharing: https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes
> Added Motion & Orientation settings on iOS to enable the DeviceMotionEvent and DeviceOrientationEvent events.
>
> Removed support for the expired Do Not Track standard to prevent potential use as a fingerprinting variable.


All the info below is from the frame of reference of Google Analytics, so, please keep in mind that someone who hasLied about their OS or browser, etc. May cause the analytics data to become untrustworthy. But even taking that into consideration, the below warrants discussion.





The sample set is from over 4,000,000 analytics events. From the last couple of months or so.

Here are the things which jump out:

**-- Broken down by Mobile Device Info --**

**hasLiedResolution** 
Of all hasLiedResolution events tracked, (over 16,000), the highest density is Apple iPad at 69.2% of Ipad users being flagged as hasLiedResolution.
This makes up 93.9% of all hasLiedResolution events tracked from mobile users as being iPads.

Apple iPhone is the next up to bat with 3.96%, and the remaining 2.11% spread across all other mobile devices combined.
--> 3.96% is on the high end of what I would expect for percentages by this breakdown, but within a possible range for bots and crawlers, etc.

**hasLiedOS**
The numbers are smaller here, with only ~1000 events tracked, and not too crazy, but I wanted to share anyways.
Only 0.75% of all data showed hasLiedOS = true. That sounds very normal, however, of the 'true' data, 64.08% were Iphones.
This could also make sense, as Iphones are likely a target for click fraud or crawler type spoofing. 

**-- Broken down by Browser --**
The only thing that jumps out is that Safari is showing as being the source of 89.98% of all  hasLiedResolution events. (Again, over 16,000 total). This obviously goes hand in hand with iPad use.





### Fingerprint data

Unfortunately, I do not actually own an IPad, but will see about getting my hands on one for testing.


### Summary
Not sure if Apple is doing something to impact these elements, or if it's simply an issue with iPad detection in fingerprintjs2.

I did have a thought: How do iPads handle windowed browsers for multitasking compared to how fingerprintJS2 detects hasLiefResolution?

**Comment by jonashaag** [comment]
Could also be a bug in the library.

**Comment by jwest75674** [comment]
For sure, it's possible the implementation is pretty quick and dirty at best. Here's what I am using. (This is inside of the Google Tag Manager, all the rest is native Google Tag Manager tags, etc, nothing custom)
```
<script src="https://cdn.jsdelivr.net/npm/fingerprintjs2@2.0.6/dist/fingerprint2.min.js"></script>
<script type="text/javascript">

var fingerprint; // Variables to allow the Google Tag Manager to capture the data after this script has ran.
var adblock;
var liedLanguages;
var liedResolution;
var liedOS;
var liedBrowser;

if (window.requestIdleCallback) {
	requestIdleCallback(function () {
		Fingerprint2.get(function (components) {
			var values = components.map(function (component) {
					return component.value
				})
				fingerprint = Fingerprint2.x64hash128(values.join(''), 31);
			adblock = components[20].value;
			console.log(adblock);
			liedLanguages = components[21].value;
			console.log(liedLanguages);
			liedResolution = components[22].value;
			console.log(liedResolution);
			liedOS = components[23].value;
			console.log(liedOS);
			liedBrowser = components[24].value;
			console.log(liedBrowser);

			dataLayer.push({
				"event": "gtm.fingerprint" // This event triggers the tag manager to get the variable data and send it to Google analytics.
			});
		})
	})
} else {
	setTimeout(function () {
		Fingerprint2.get(function (components) {
			var values = components.map(function (component) {
					return component.value
				})
				fingerprint = Fingerprint2.x64hash128(values.join(''), 31);
			adblock = components[20].value;
			console.log(adblock);
			liedLanguages = components[21].value;
			console.log(liedLanguages);
			liedResolution = components[22].value;
			console.log(liedResolution);
			liedOS = components[23].value;
			console.log(liedOS);
			liedBrowser = components[24].value;
			console.log(liedBrowser);

			dataLayer.push({
				"event": "gtm.fingerprint"
			});
		})
	}, 500)
}
</script>
```

**Comment by jonashaag** [comment]
> For sure, it's possible. The implementation is pretty quick and dirty at best.

No no I'm talking about a bug in fingerprintjs2. Can you by any chance check the "has lied" components with an untampered-with iPad/iPhone? I'll check with my iPhone later.


> Just doing some research, found a few elements which are quite compelling:
> [...]

Umm, we're already using all of these things :)

**Comment by jwest75674** [comment]
Thanks jonashaag!

> -No no I'm talking about a bug in fingerprintjs2. Can you by any chance check the "has lied" components with an untampered-with iPad/iPhone? I'll check with my iPhone later.

> Umm, we're already using all of these things :)
My apologies, what I meant was, those are two sources from Apple directly that indicate they are putting in place measures to defeat fingerprinting for Safari. This is compelling, in that it supports what the data is showing, and makes me think that the issue is not a bug in finerprintjs2, just Apple adding extra privacy measures.

I've been asking around, trying to get an ipad, have one lined up and will report back once I get my hands on it.

I am going to see about temporarily expanding my data capture to create a history of more individual fingerprint components by JSON.stringfy ing the full component variable on each page load. In a few days, I should be able to share the most likely component setups to flag as liedOS.
--> This can't be done through analytics, to will be passing data to BigQuery, and will query it once some time has passed to share the findings here.

JW

**Comment by Finesse** [comment]
The `hasLied...` components are removed in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0) because they give no information when used in addition to other components.

Safari tracking prevention prevents placing cookies in some scenarios but it doesn't thwart fingerprinting.
