### ISSUE TITLE
detectScreenOrientation flag is backwards

### ISSUE THREAD

**Issue by davidsturman** [fingerprintjs/fingerprintjs#390]
### Problem description

- The detectScreenOrientation is backwards. In the code, if the flag is true you return the ratio of whichever dimension is greater over whichever dimension is smaller. This returns the same answer regardless of screen orientation. If the flag is false, you return width/height which changes depending on screen orientation. I think you want the if clause the other way around.

### Fingerprintjs2 version and devices used

[ ] I can reproduce the bug in [fingerprintjs master](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js)
[ ] I can reproduce the bug on these devices: iPhone XYZ

### Minimal reproducing example

[ ] I can reproduce the bug with this jsfiddle: https://jsfiddle.net/L2gLq4rg/
[ ] Alternatively, I have provided a jsfiddle that reproduces the bug here: <jsfiddle url>

**Comment by jonashaag** [comment]
Thanks for the input.

This is a matter of documentation. Feel free to change documentation in the wiki or send a PR.

**Comment by davidsturman** [comment]
I actually think the code should be switched or the option named changed. As it is,
{detectScreenOrientation:true} does not detect the screen orientation and false does.
Either change switch the results of the if statement or the name of the option to ignoreScreenOrientation. Since you I can imagine not wanting to break old code, I'd add a new ignoreScreenOrientation option that does the right thing and indicate in the documentation that the detectScrrenOrientation is reversed. I'm happy to provide the code and doc if you'd like.
 -djs

**Comment by jonashaag** [comment]
Agreed, PR welcome :) feel free to add a deprecation warning to the old option name

**Comment by jonashaag** [comment]
Can you make the changes based on #388

**Comment by GrosSacASac** [comment]
I added you to Collaborator list so you can push directly to the branch https://github.com/GrosSacASac/fingerprintjs2/tree/errors-and-promise to change the current PR

**Comment by Finesse** [comment]
I've added a clarification to the readme. Renaming an option will be a major change so the option won't be changed until v3. We will consider this confusion in the v3 design.

**Comment by Finesse** [comment]
The flag is removed in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0). Screen orientation is considered automatically, you don't need to worry about it.
