### ISSUE TITLE
Use low-power GPU on MacOS

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#391]
https://github.com/Valve/fingerprintjs2/issues/226#issuecomment-421978334
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63#Canvas_and_WebGL

**Comment by abram27** [comment]
I tried implementing this which initially seemed to work pulling the lower power GPU in the fingerprint, but after opening other apps it switched over to the high-performance GPU in the same browser after a refresh.  The powerPreference attribute is only a hint and doesn't guarantee use of a certain GPU so not sure if it will solve more issues than it creates.  WebGL spec states: **This **may** influence which GPU is used in a system with multiple GPUs.**  As a note if others test it out for themselves - in the WebGL spec _webglcontextlost_ and _webglcontextrestored_ need to be implemented for the attribute to take effect.

WebGL spec: [https://www.khronos.org/registry/webgl/specs/latest/1.0/]

**Comment by Valve** [comment]
Closing as WebGL has been removed from v3.

**Comment by Finesse** [comment]
@Valve As far as I understand, it affects canvas too, doesn't it?

**Comment by Valve** [comment]
It does, but using canvas never triggers a GPU switch, so it affects it in theory, but not in practice.
