### ISSUE TITLE
Split fingerprintjs into multiple files

### ISSUE THREAD

**Issue by GrosSacASac** [fingerprintjs/fingerprintjs#394]
I imagine a structure as follow:

## Structure
```
package.json
...
fingerprintjs2.js

components
    componentA.js
    componentB.js
    componentC.js
    ...etc

hash
   murmur.js
```

fingerprintjs2.js imports every component and murmur so that the result is the same. This could be a non breaking change. The components don't need to import fingeprint.js (everything needed is provided in options argument)

## Bundler

As bundler I think rollup is appropriate https://rollupjs.org/guide/en

It can produce standard iife, umd and commonjs output

> Publishing ES6 Modules
To make sure your ES6 modules are immediately usable by tools that work with CommonJS such as Node.js and webpack, you can use Rollup to compile to UMD or CommonJS format, and then point to that compiled version with the main property in your package.json file. If your package.json file also has a module field, ES6-aware tools like Rollup and webpack 2+ will import the ES6 module version directly.

New file outputs:

```
dist/fingerprintjs2.iife.js   for <script>
dist/fingerprintjs2.min.js   same as before for commonjs
dist/fingerprint2.es.js for <script type="module"> and rollup, webpack
```

New pacakage.json field
```
{
  "module": "dist/fingerprint2.es.js"
}
```
Fixes
https://github.com/Valve/fingerprintjs2/issues/387
https://github.com/Valve/fingerprintjs2/issues/320
https://github.com/Valve/fingerprintjs2/issues/146 ?

**Comment by jonashaag** [comment]
Sounds good! I wonder if there’s a way to allow for custom minimal builds that don’t include the code for components you’re not using.

**Comment by Valve** [comment]
I did splitting into multiple files for the pro version. I used web pack though, I like it more than rollup. 
Once I get some time I'll be able to back port this into the OSS version.

**Comment by pisaq** [comment]
@Valve @GrosSacASac was the case ever resolved? 
I'm having now same issue :(

**Comment by Valve** [comment]
V3 will be implemented in TypeScript and fully modular.

**Comment by Finesse** [comment]
Done in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0)
