### ISSUE TITLE
New component canPlayType

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#395]
Use `canPlayType` to check for video format/codec availability.

Seems to be browser dependent but doesn't change in incognito mode.

Example code with list of mime types I've harvested from various sources: https://gist.github.com/jonashaag/5670d72a1d471552a4a5ac87414957bb

Further sources for mime types:
https://wiki.whatwg.org/wiki/video_type_parameters
http://www.rfc-editor.org/rfc/rfc2361.txt

**Comment by Finesse** [comment]
@Valve What do you think? Will it give an extra entropy? Should we implement it in v2 or v3?

**Comment by Valve** [comment]
@Finesse Yes, should be researched for future versions, let's keep it open.

**Comment by chris124567** [comment]
Has the research been finished?  I'd be happy to write a PR adding and testing this (on another note I think there's better ways to get entropy from this than counting the "maybe" and "probably"s returned by canPlayType like the sample code does).

**Comment by Finesse** [comment]
@chris124567 Looks like no research was conducted. It will be great if you do the research and make a PR. What the research must show:

- The source is very stable (gives the same value in a browser instance unless the user changes OS/browser settings)
- The source gives the same result in regular and incognito modes of all [supported browsers](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/browser_support.md)
- The source identifies something other than browser and its version. For example, if the result depends on device, OS, OS setting, installed codecs and drivers, etc.

You can use BrowserStack Live to do the research (I don't know if it's available for free). It the source matches all the criteria, then it makes sense to add it to the code.

**Comment by chris124567** [comment]
OK. Sounds good. I'll finish this in the next week or two

**Comment by chris124567** [comment]
After doing some research (https://docs.google.com/document/d/1QgcwI7n30kE0sDZzZmd_bO9ouKdPOfCGJh777X6kZbg/edit?usp=sharing) I do not think this is worth adding.  While the results are stable across sessions/incognito mode, it seems that they are basically just a proxy for browser version.

 If anyone is interested, the code I used to test is available at https://github.com/chris124567/fingerprintjs/blob/7703f4f670c12024dcb9d2214772e1a1495a2bdc/src/sources/codecs.ts.

**Comment by Finesse** [comment]
@chris124567 Thank you very much! Since the API doesn't give enough entropy, I'm closing the issue.
