### ISSUE TITLE
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting.

### ISSUE THREAD

**Issue by 0c0c0f** [fingerprintjs/fingerprintjs#435]
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting.

firefox
![image](https://user-images.githubusercontent.com/34776076/53538460-adbc6580-3b48-11e9-85ba-0f80afe7b57a.png)

**Comment by Finesse** [comment]
@0c0c0f Does it prevent the `webgl` component from returning a result? I can't reproduce it. Please give more information on how to reproduce.
