### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)

### ISSUE THREAD

**Issue by Gold-pig** [fingerprintjs/fingerprintjs#453]
Audio fingerprint timed out. Please report bug at https://github.com/Valve/fingerprintjs2 with your user agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8".

**Comment by Valve** [comment]
@PhotographerGuo thanks for the bug report, I'm going to look into it shortly

**Comment by harrywebdev** [comment]
Another one (same thing) noticed in Sentry logs

```
Audio fingerprint timed out. Please report bug at https://github.com/Valve/fingerprintjs2 with your user agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0".
```
