### ISSUE TITLE
Screen resolution, available and total have different orientation

### ISSUE THREAD

**Issue by tjmjansen** [fingerprintjs/fingerprintjs#454]
Simple issue, i had to turn of screen orientation detection because of chaning fingerprints between 1.8.x and 2.0.x
now i see that the orientation is different between screenResolution and availableScreenResolution

**Comment by Valve** [comment]
@tjmjansen thanks for the bug report, I'm going to look into it shortly

**Comment by Finesse** [comment]
@tjmjansen Does the bug still occur in the latest version (2.1.2)? Please provide more details: steps to reproduce, expected result and actual result.
