### ISSUE TITLE
The "fonts" component shows different results all the time

### ISSUE THREAD

**Issue by COOLak** [fingerprintjs/fingerprintjs#455]
### Scenario

- What causes the fingerprint to change?
Parameters "fonts" and "enumerateDevices" show different results almost every time (only in production, not applicable to test page index.html)

- What device and browser are you using?
Windows 7 x64 PC, Firefox 66.0.2

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
Master

### Fingerprint data

1.

```
94ac6e240d354bda5a9ae6c86d893d3d
webdriver = false
colorDepth = 24
deviceMemory = not available
pixelRatio = 1
hardwareConcurrency = 8
screenResolution = 1920,1080
availableScreenResolution = 1920,1040
sessionStorage = true
localStorage = true
indexedDb = true
addBehavior = false
openDatabase = false
cpuClass = not available
platform = Win32
doNotTrack = unspecified
canvas = canvas winding:yes,canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAARLUlEQVR4nO3c30sj+p/f8eef0YsWvh
webglVendorAndRenderer = Google Inc.~ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
adBlock = false
hasLiedLanguages = false
hasLiedResolution = false
hasLiedOs = false
hasLiedBrowser = false
touchSupport = 0,false,false
fonts = Arial,Arial Black,Arial Narrow,Arial Rounded MT Bold,Arial Unicode MS,Book Antiqua,Bookman Old Style
fontsFlash = swf object not loaded
audio = 35.7383295930922
enumerateDevices = id=jfVAL8oTVjbjtuwbxvN4ylgRvB/Z8Ir9z7iTe4KZa0w=;gid=;videoinput;,id=l0beDlXhiPlShY/Xgio4YPNO68ZOS1Bv
```

2. 

```
86142947a0736898caba4e28f13e313c
webdriver = false
colorDepth = 24
deviceMemory = not available
pixelRatio = 1
hardwareConcurrency = 8
screenResolution = 1920,1080
availableScreenResolution = 1920,1040
sessionStorage = true
localStorage = true
indexedDb = true
addBehavior = false
openDatabase = false
cpuClass = not available
platform = Win32
doNotTrack = unspecified
canvas = canvas winding:yes,canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAARLUlEQVR4nO3c30sj+p/f8eef0YsWvh
webglVendorAndRenderer = Google Inc.~ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
adBlock = false
hasLiedLanguages = false
hasLiedResolution = false
hasLiedOs = false
hasLiedBrowser = false
touchSupport = 0,false,false
fonts = Arial,Arial Rounded MT Bold,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambria
fontsFlash = swf object not loaded
audio = 35.7383295930922
enumerateDevices = id=uY2Slk7jvnaaHXbOFLyMq5kUanaekNlbvaeB7jBDgJs=;gid=;videoinput;,id=weKpbpAX8bIxRakln+0reLR9woPLOmN9
```

The two fingerprints are from exactly the same browser and taken within a minute from one another. Parameters "fonts" and "enumerateDevices" show different results, as can be seen.

**Comment by jonashaag** [comment]
Thanks for the report.

Known issue for enumerateDevices.

Maybe related to #441 for the Arial Black font missing issue.

**Comment by rganko** [comment]
Somehow [groupId](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/groupId) is changing on every fingerprint2 run on Firefox.

Easy to check with (on every page refresh):
 `const [{ groupId }] = await navigator.mediaDevices.enumerateDevices();`

The idea would be to exclude `enumerateDevices` from fingerprint2

`
    const options = {
      excludes: {
        enumerateDevices: true,
      }
    };
`

P.S. how about to remove groupId from component? is it so significant?

**Comment by zmts** [comment]
Same issue. Fix it like @rganko by adding `enumerateDevices ` to excludes
This is my getHash function. I hope someone find it helpful :)
https://gist.github.com/zmts/b26ba9a61aa0b93126fc6979e7338ca3

**Comment by Finesse** [comment]
The `enumerateDevices` component is known to be unstable therefore it's excluded by default.

I'll investigate the fonts issue later.

**Comment by Finesse** [comment]
Please try to reproduce it with [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0). Closing the issue in favor of https://github.com/fingerprintjs/fingerprintjs/issues/366.
