### ISSUE TITLE
Docs: Which options depend on HTTPS?

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs#459]
Some options only work with HTTPS. Document this in the list of options.

**Comment by medha-yadav** [comment]
I would like to work on this.Could you please guide.

**Comment by jonashaag** [comment]
Sure. For starters, run fingerprintjs with a configuration that includes all components and run it on a website with HTTP and HTTPS, and compare the results.

**Comment by jonashaag** [comment]
Note that some components change every time you refresh the page, even if not switching between HTTP and HTTPS, so first check what components stay constant when refreshing the page.

**Comment by Finesse** [comment]
Note: Ngrok can be used to establish a pair of HTTP and HTTPS servers based on your local HTTP server quickly.

**Comment by Finesse** [comment]
I've checked the components on all platforms except Android. I need an Android device to check it. Could anybody please check the components on Android browsers?

**Comment by Valve** [comment]
Can you check it on BrowserStack?

**Comment by Finesse** [comment]
Yes, I guess. I haven't tried it before. Will try later. But since we don't support HTTP, do we need this list?

**Comment by Valve** [comment]
we need it for v2, don't need it for v3.
we'll keep maintaining v2 for a long time.

**Comment by JuroUhlar** [comment]
Closing as no longer relevant after discussing with @Finesse.
