### ISSUE TITLE
n.renderedBuffer.getChannelData(...).slice is not a function

### ISSUE THREAD

**Issue by Will233** [fingerprintjs/fingerprintjs#462]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 

I use fingerprint2 (npm 1.8.5) in my vuejs project,
```
  new Fingerprintjs2().get((browserId) => {
    domSomething(browserId)
  })
```
in some android devices
error  happened  like this
```
TypeError: n.renderedBuffer.getChannelData(...).slice is not a function
at OfflineAudioContext.r.oncomplete
``` 
- What device and browser are you using?
```
Mozilla/5.0 (Linux; Android 5.1; OPPO R9m Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36;
```
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
 fingerprint2 (npm 1.8.6)

**Comment by tianchouczl** [comment]
I had the same problem.

**Comment by Finesse** [comment]
@tianchouczl @Will233 Does the problem happen in the latest version of FingerpringJS (2.1.2)?

@Valve @jonashaag Do we support v1?

**Comment by Valve** [comment]
@Finesse we support v1 for bugfixes only.

**Comment by Will233** [comment]
@Finesse  FingerpringJS (2.1.2) has no problem , I use 2.x now.
