### ISSUE TITLE
hasLiedLanguages may return wrong value for Chrome and legacy Android (4.x and older)

### ISSUE THREAD

**Issue by mads1980** [fingerprintjs/fingerprintjs#507]
Chrome as well as the stock Android AOSP browser not not guarantee navigator.language == navigator.languages[0] which is what FingerprintJS is checking with hasLiedLanguages.

References:
https://caniuse.com/#search=languages 

Issue 101138: Review what to do about navigator.language : UI language vs the top Accept-Language 
https://bugs.chromium.org/p/chromium/issues/detail?id=101138

**Comment by mads1980** [comment]
In Chrome, navigator.language is the language of the browser UI, and is not guaranteed to be equal to navigator.languages[0].

**Comment by Valve** [comment]
@mads1980  thanks for the report, a PR would be very much appreciated!

**Comment by mads1980** [comment]
Basically the test should be skipped for Chrome and any User-Agent containing "Android 1.", "Android 2.", "Android 3.", or "Android 4."

The problem is that Chrome has such a large market share, that the test would become meaningless for the vast majority of cases. Also many User-Agents now contain "Chrome" since they are Chromium-based (Samsung Browser, newer Opera builds, now also Edge is transitioning to Chromium) and it is uncertain whether their behaviour follows stock Chrome or not.

Perhaps the feature should be left as-is, and document that it is unreliable because of the aforementioned issues. The difference between navigator.language and navigator.languages[0] still adds a bit of useful entropy, even if "hasLiedLanguages" seems to imply fraud/spoofing when this is not the case, at least for Chrome and old AOSP browsers.

**Comment by Finesse** [comment]
@mads1980 Seems like it's fixed in Chrome 85. My system language is English, I've set Russian and Afrikaans languages to the language setting of Chrome and have got `navigator.languages = ['ru', 'af']` and `navigator.language = 'ru'`. Anyway I think it's a source of entropy rather than a bug.

@Valve @jonashaag BTW why does FingerprintJS has `hasLiedLanguages` component and no `languages` component? I would leave the `language` component, add `languages` and discard `hasLiedLanguage`.

**Comment by Valve** [comment]
It has both: https://github.com/fingerprintjs/fingerprintjs2/blob/master/fingerprint2.js#L414

**Comment by Finesse** [comment]
> It has both: https://github.com/fingerprintjs/fingerprintjs2/blob/master/fingerprint2.js#L414

@Valve I see no `languages` component. `navigator.languages` participates only in the `hasLiedLanguages` component. I think the content of `navigator.languages` is a good source of entropy.

Do we even need `hasLied...` components? Seems like they add no entropy.

**Comment by Valve** [comment]
Yes, you're right, I confused it with our Pro version agent, which does that. Thanks. Please mark for v3 as we'll add it there.

**Comment by Finesse** [comment]
The `hasLiedLanguages` component is removed in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0) because is gives no entropy when used with other components
