### ISSUE TITLE
Time-Based Device Fingerprinting

### ISSUE THREAD

**Issue by drstyv** [fingerprintjs/fingerprintjs#522]
Maybe this is something that could be considered to be added to the fingerprint?

https://dl.acm.org/doi/10.1145/3243734.3243796

**Comment by Valve** [comment]
@drstyv thanks for the link, we'll look into it

**Comment by Finesse** [comment]
Thank you for the hint! I've found the full article at http://www.eurecom.fr/fr/publication/5664/download/sec-publi-5664.pdf and http://s3.eurecom.fr/docs/ccs18_iskander.pdf. Also I've found a short presentation: https://cmpe253-winter19-01.courses.soe.ucsc.edu/system/files/attachments/Clock-Zheng.pptx.

**Comment by Finesse** [comment]
I can't say whether and when we'll leverage it. We've taken it into account. The issue requires no more action from us so I'm closing it.

**Comment by EvMac0** [comment]
Some of my work: https://github.com/EvMac0/Repeat-ClockAroundTheClock
