### ISSUE TITLE
IPhone safari fingerprint change with orientation.

### ISSUE THREAD

**Issue by LadislavSopko** [fingerprintjs/fingerprintjs#534]
### Scenario

IPhone safari fingerprint change with orientation.

### Fingerprint data

problem is due to wrong: hasLiedResolution 

I fixed it:

```js
 var getHasLiedResolution = function () {
    // fix: laco we need sort resolution first due to mobile orientations
    var available = [window.screen.availWidth, window.screen.availHeight]
    available.sort().reverse()
    var resolution = [window.screen.width, window.screen.height]
    resolution.sort().reverse()   

    return resolution[0] < available[0] || resolution[1] < available[1]

    //return window.screen.width < window.screen.availWidth || window.screen.height < window.screen.availHeight
  }
```

regards

**Comment by jonashaag** [comment]
Thanks for reporting, I think that's a bug in the code. We should be using the orientation-aware resolution getters.

**Comment by LadislavSopko** [comment]
Ok, 
for now with my fix (workaround),  it goes well.

**Comment by abrahamjuliot** [comment]
@LadislavSopko is this a Safari only issue/fix?

**Comment by Finesse** [comment]
@LadislavSopko What device and iOS version did you use? I can't reproduce it on iPhone SE 1 with iOS 13.6.1

**Comment by LadislavSopko** [comment]
It was a bit time ago, it should be Iphone8 with iOS 13.6.x and browser
safari

Il giorno lun 7 set 2020 alle ore 13:37 Surgie Finesse <
notifications@github.com> ha scritto:

**Comment by Finesse** [comment]
@LadislavSopko I'll double check it. I don't have an iPhone 8 so I'll use an emulator from Xcode.

**Comment by LadislavSopko** [comment]
I think is more question of safari then phone

Il giorno lun 7 set 2020 alle ore 15:24 Surgie Finesse <
notifications@github.com> ha scritto:

**Comment by Valve** [comment]
@Finesse you can also use our BrowserStack account to test.

**Comment by Finesse** [comment]
Orientation is ignored in [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0), so the fingerprint won't change
