### ISSUE TITLE
v3 release

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#545]
Requirements:

- Fully modular (support modules, IIFE, umd etc).
- Written in TS
- No IE support (remove old cruft made for IE specifically).
- Drop flash
- API-level compatible with Pro API. 
- Browserstack testing on all supported browsers
- Automatic NPM publishing for each release with GitHub actions
- Renaming fingerprintjs/fingerprintjs2 to fingerprintjs/fingerprintjs (handle NPM packages and CDN).
- Redirect from valve/fingerprintjs to fingerprintjs/fingerprintjs

**Comment by Deval520** [comment]
> Requirements:
> 
> * Fully modular
> * Written in TS
> * No IE support (remove old cruft made for IE specifically).
> * Drop flash
> * API-level compatible with Pro API.
> * Browserstack testing on all supported browsers
> * Automatic NPM publishing for each release with GitHub actions
> * GH Bot to automatically close stale issues
> * Renaming fingerprintjs/fingerprintjs2 to fingerprintjs/fingerprintjs (handle NPM packages and CDN).
> * Redirect from valve/fingerprintjs to fingerprintjs/fingerprintjs


Does the new version add new collection features?

**Comment by Valve** [comment]
@Deval520 new version is more about new architecture and code refactoring. New signals will continue to be added incrementally.

**Comment by Finesse** [comment]
The v3 is being developed at https://github.com/fingerprintjs/fingerprintjs/tree/v3

**Comment by Finesse** [comment]
Done: [v3](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.0.0). Automatic deployment will be added later.
