### ISSUE TITLE
Type definitions for @fingerprintjs/fingerprintjs / use with TypeScript

### ISSUE THREAD

**Issue by jspruance** [fingerprintjs/fingerprintjs#553]
I cannot seem to find any type definitions for the latest version '@fingerprintjs/fingerprintjs' - only for 'fingerprints2' and 'fingerprintjs'. Do any exist and is it possible to use this module with TypeScript? Thanks.

**Comment by Finesse** [comment]
The types at https://www.npmjs.com/package/@types/fingerprintjs2 and https://www.npmjs.com/package/@types/fingerprintjs are types created by somebody else, not us. We will [make our own typing in version 3](https://github.com/fingerprintjs/fingerprintjs/issues/545) that is going to be released in a couple months. Therefore we don't give support for the typing of v2.

If you need the types sooner, please see the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped) that hosts the current types for `fingerprintjs` and `fingerprintjs2`. You can open an issue there or make a pull request that adds types for `@fingerprintjs/fingerprintjs` (just copy [types/fingerprintjs2](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fingerprintjs2) to `types/fingerprintjs__fingerprintjs`).

**Comment by Finesse** [comment]
Also you can just type `declare module '@fingerprintjs/fingerprintjs'` in a `.d.ts` file, and you'll be able to use the library with TypeScript and without errors from TypeScript.

**Comment by jspruance** [comment]
Awesome, thanks for the help. Look forward to v3.
