### ISSUE TITLE
'deafult' is not exported by fingerprint2.js

### ISSUE THREAD

**Issue by vyorkin** [fingerprintjs/fingerprintjs#555]
Hello! I've just updated the package name from `fingerprint2` to `@fingerprintjs/fingerprintjs` as was suggested by the message I saw in a terminal when installing the `fingerprintjs2` package.

I'm trying to import the fingerprint lib:

```
import Fingerprint2 from '@fingerprintjs/fingerprintjs';
import type { Component } from '@types/fingerprintjs2';
```

Getting the following error:

```
[!] Error: 'default' is not exported by node_modules/@fingerprintjs/fingerprintjs/fingerprint2.js
```

Maybe I'm doing something wrong?
Is there a usage example? 
(also, I have to use the old name for typings, it might be a good idea to update those as well)

**Comment by Finesse** [comment]
@vyorkin What exactly emits the error in your case? TypeScript, Webpack, Babel or something else?

The only thing that really can brake after renaming the package is the lack of TypeScript typing for `@fingerprintjs/fingerprintjs`. If it's TypeScript in your case, then see our position and recommendations on this issue at https://github.com/fingerprintjs/fingerprintjs/issues/553#issuecomment-697108074. If not, then please provide more details, a minimal reproducible example would be great.

**Comment by vyorkin** [comment]
Thanks for the feedback! I've found that it was due to missing `external`'s in my rollup config (so it was a rollup error in my case). Sorry for taking your time, the error is completely unrelated to fingerprintjs package.
