### ISSUE TITLE
Implement v3 open demo

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#556]
Should show the visitor ID and have a nice design (design will be provided separately).
Do after v3 is released.

**Comment by Finesse** [comment]
We can combine it with a live playground for development

**Comment by Finesse** [comment]
I've implemented a playground/demo. To see, switch to [`v3` branch](https://github.com/fingerprintjs/fingerprintjs/tree/v3), then run:

```bash
yarn install
yarn playground:start
```

And open http://localhost:8080
