### ISSUE TITLE
webglVendorAndRenderer missing in v3?

### ISSUE THREAD

**Issue by C0kkie** [fingerprintjs/fingerprintjs#567]
Hello,

in v2 there was a key named webglVendorAndRenderer to see the GPU. i cant find it in v3 anymore?

**Comment by Valve** [comment]
Hi @C0kkie 
Thanks for submitting an issue.
Yes, we removed WebGL from v3 as it [created more problems than solved](https://github.com/fingerprintjs/fingerprintjs/issues?q=is%3Aissue+webgl)

It made the library slower, less stable and didn't add much entropy.

I'm closing this issue, but please feel free to reopen with additional comments or thoughts.
