### ISSUE TITLE
Audio fingerprint timeout in Firefox on a desktop Linux

### ISSUE THREAD

**Issue by wolfdark37** [fingerprintjs/fingerprintjs#580]
Audio fingerprint timed out. Please report bug at https://github.com/Valve/fingerprintjs2 with your user agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0". 5f0c548ec826e0abb60de870:1:26982

**Comment by Finesse** [comment]
@wolfdark37 Thanks for the report. Does the timeout happen in your browser always or occasionally?

**Comment by Finesse** [comment]
I try Firefox 82 on Ubuntu 20.04 and can't reproduce it. @wolfdark37, please provide more details and steps to reproduce.

**Comment by Finesse** [comment]
Closing due to inability to reproduce and the lack of response
