### ISSUE TITLE
AdBlocker and PRO version - FAIL

### ISSUE THREAD

**Issue by Neolo** [fingerprintjs/fingerprintjs#587]
# Scenario
- What's the scenario, what happens and what did you expect to happen?
Just open the page
- What device and browser are you using?
Opera Mac with AdBlocker external and internal 
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
PRO trial v3
### Fingerprint data
N/A

AdBloker is simply takes down your PRO version. What to pay $100 for? Near 90% of visitors have adblocker installed.

ERRR trackers blocked: 1

`fp.min.js:8 POST https://api.fpjs.io/ net::ERR_BLOCKED_BY_ADBLOCKER
(anonymous) @ fp.min.js:8
Q @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
r @ fp.min.js:8
ce @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
r @ fp.min.js:8
ue @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
(anonymous) @ fp.min.js:8
a @ fp.min.js:8
Promise.then (async)
c @ fp.min.js:8
(anonymous) @ fp.min.js:8
r @ fp.min.js:8
get @ fp.min.js:8
onFingerprintJSLoad @ (index):32
Promise.then (async)
onload @ (index):42
fp.min.js:8 Uncaught (in promise) Error: Network connection error
    at fp.min.js:8
    at fp.min.js:8
    at Object.throw (fp.min.js:8)
    at u (fp.min.js:8)`

**Comment by Finesse** [comment]
@Neolo There are solutions for this problems: [CNAME](https://dev.fingerprintjs.com/docs/cname) or [a CloudFlare integration](https://dev.fingerprintjs.com/docs/cloudflare). Please contact [pro support](mailto:support@fingerprintjs.com) for more details.
