### ISSUE TITLE
No visitorId for mobile device

### ISSUE THREAD

**Issue by erikdemarco** [fingerprintjs/fingerprintjs#589]
Hi,

Why it only shows visitorid for desktop? and no visitorid when accessed with mobile device?

**Comment by Finesse** [comment]
@erikdemarco The library works on mobile devices with browsers listed in the [browser support guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/browser_support.md). Please tell your mobile device and provide steps to reproduce the problem.

**Comment by Finesse** [comment]
Closing due to the lack of response
