### ISSUE TITLE
Same finger in two computes

### ISSUE THREAD

**Issue by Hukeqing** [fingerprintjs/fingerprintjs#593]
### Scenario

I have two computers(Windows 7 Chrome 85.0.4183.121 64bit), which are highly similar and in the same local area network. I tried to use these two computers to access the demo website of this project, and then I got two identical IDs

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by Valve** [comment]
Hi @Hukeqing 

Thanks for trying out open-source product!
It's possible that two different devices generate the same fingerprint.
If you want increased accuracy, please try our FingerprintJS Pro version here: https://dashboard.fingerprintjs.com/signup
Pro version has a significantly higher accuracy.

I'm closing this issue now as this behavior is expected.
