### ISSUE TITLE
Uncaught ReferenceError: initFingerprintJS is not defined - at line 1

### ISSUE THREAD

**Issue by erikdemarco** [fingerprintjs/fingerprintjs#594]
I'm using sentry to track javascript error. Why very small percentage (~3%) of my visitor get this error?

My script is like this:
```
<script>
  function initFingerprintJS() {
    // Start loading FingerprintJS here
  }
</script>
<script src="//cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
<script async src="//cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js" onload="initFingerprintJS()"></script>
```

**Comment by Finesse** [comment]
@erikdemarco What's the error message and call stack? What are the user agents that get the error (Sentry must show them)?

**Comment by Finesse** [comment]
Looks like you use the code incorrectly. Probably, you define `initFingerprintJS` after `<script async src="//cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js" onload="initFingerprintJS()"></script>`. Please share more of your code.

**Comment by Finesse** [comment]
Closing due to the lack of response
