### ISSUE TITLE
adblock.ts does not reliably detect Adblock Plus and uBlock Origin

### ISSUE THREAD

**Issue by NikolaiT** [fingerprintjs/fingerprintjs#598]
### Scenario

- What's the scenario, what happens and what did you expect to happen?

I am using uBlock Origin but the fingerprint detector https://github.com/fingerprintjs/fingerprintjs/blob/master/src/sources/adblock.ts tells me that no adblock software is being used. Detection also does not work with Adblock Plus.

Expected was the detection of said adblock software.

- What device and browser are you using?

Firefox/84.0  with Adblock Plus v3.10.1

Chrome/86.0.4240.75 with uBlock Origin v1.31.2

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

fingerprintjs version "3.0.4"

### Suggested solution: 

This is my own solution: https://github.com/NikolaiT/adblock-detect-javascript-only/blob/master/index.js

**Comment by Finesse** [comment]
This source is disabled now. Chrome and Firefox disable extensions (including Adblock) in incognito mode so ad block detection can’t be used as entropy source, see https://github.com/fingerprintjs/fingerprintjs/issues/405.
