### ISSUE TITLE
Make the library not refer global variables (e.g. window) until load() is called

### ISSUE THREAD

**Issue by wenzi0github** [fingerprintjs/fingerprintjs#602]
### Scenario

I use fingerprintjs in nextjs(nextjs is a ssr react), it will show the error:

> ReferenceError: window is not defined

fingerprintjs version is:

```
"@fingerprintjs/fingerprintjs": "^3.0.3",
```

what can i do?

**Comment by Finesse** [comment]
Since FingerprintJS is a client-side-only library, make NextJS run it only on client side. Refer to NextJS documentation to learn how to do it. Probably, [this](https://flaviocopes.com/nextjs-server-client-code/) or [this](https://github.com/vercel/next.js/issues/2473) will help.

**Comment by wenzi0github** [comment]
<img width="1227" alt="11" src="https://user-images.githubusercontent.com/8475373/104532225-b0e07200-564a-11eb-941b-78e58bb6d2cb.png">

in this pic, I just import @fingerprintjs/fingerprintjs and then do nothing, it will be a mistake.

can get window in load function, not get window or document immediately? this I can exec load function in client side.

**Comment by Finesse** [comment]
You are right, FingerprintJS uses `window` when being imported. FingerprintJS doesn't actually need `window` before `load()` is called, so this issue can be solved. I'll return to it later. For now, please try to use [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) so that FingerprintJS is imported only on client side, and tell me whether it helps.

**Comment by wenzi0github** [comment]
I will try use `plain dynamic import` as soon.

my plan is to create a user behavier report component based on fingerprintjs, then use the report component in other activities, if I used `plain dynamic import`, i don't kown if there has a baseUrl question.

I'm more looking forward to the new version.

**Comment by Finesse** [comment]
Then try to create a plain React component that uses FingerprintJS and import the component using [NextJS dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) (see the "With no SSR" section, it's right what you need).

**Comment by Finesse** [comment]
The fixed is published in v3.0.6. Update the package to get it:

```bash
npm i @fingerprintjs/fingerprintjs@latest
# or
yarn add @fingerprintjs/fingerprintjs@latest
```

**Comment by adkaushik** [comment]
Using version 3.1.2 in nextjs and still facing this issue

**Comment by Finesse** [comment]
@adkaushik Show your code
