### ISSUE TITLE
指纹生成有问题

### ISSUE THREAD

**Issue by lmq352489099** [fingerprintjs/fingerprintjs#603]
每次生成的指纹都不同

**Comment by Finesse** [comment]
We don't speak Chinese. Please make make an issue in English, you can use [Google Translate](https://translate.google.com/?sl=zh-CN&tl=en) if you don't speak English.

**Comment by wuchuguang** [comment]
Each time you generate a different fingerprint

**Comment by Finesse** [comment]
You provide very little information, so we can't check your case. Please tell the following:

1. The operating system and browser name and versions that you use.
2. The address of the page where you get the different fingerprints.
2. The components that form a pair of falsely different fingerprints. You can get the components at https://fingerprintjs.github.io/fingerprintjs
