### ISSUE TITLE
Request for info - Is it possible to get same fingerprint for two different browsers?

### ISSUE THREAD

**Issue by 1ManSmoking** [fingerprintjs/fingerprintjs#605]
Hi,

In the open source version, is it possible to get same fingerprint on two completely different browsers/computers?
I mean two guys buy the same mac laptop on the same day, unpack it, connect to the same wifi and the first thing they do is browse to my website from safari.
Is it possible they will both have the same fingerprintid?

Thanks a lot!
Eli

**Comment by Finesse** [comment]
Yes, it's possible that they will get the same fingerprint. But it's possible to tell these very similar guys from each other using FingerprintJS Pro due to some advanced server-side techniques.
