### ISSUE TITLE
[v2] "getextension" is not available for webgl field (bug introduced in #176)

### ISSUE THREAD

**Issue by BafS** [fingerprintjs/fingerprintjs#611]
Upgrading to the last v2 version (at the time 2.1.2) added an issue with some browser (probably _TOR browser_), there is an error on the "webgl" field: `error: permission denied to access property "getextension"` when "getextension" is not available.

Downgrading to v2.1.0 fixed the issue, the bug was introduced in #176 (PR #484)

**Comment by Finesse** [comment]
Could you please provide a couple of user agents of the cases where the error happen

**Comment by BafS** [comment]
Unfortunately I'm not able to reproduce either, the users agents are firefox or firefox mobile, I'm wondering if it's not an addon or some sort of race condition ?

**Comment by Finesse** [comment]
@BafS I've fixed the error in IE10. Probably, that will fix your error too. Please try the version from https://github.com/fingerprintjs/fingerprintjs/blob/hotfix/v2-webgl-error/fingerprint2.js and tell me if it helps.

**Comment by Finesse** [comment]
Closed by https://github.com/fingerprintjs/fingerprintjs/pull/618

**Comment by BafS** [comment]
Sorry @Finesse, I missed your message, I didn't have the time to try your patch yet but I will let you know if the bug is still there when we upgrade. Thanks a lot for your fix !

**Comment by Finesse** [comment]
@Finesse Here is a link to the script version with the fix: [fingerprintjs/fingerprintjs/5019fb8c4b3a1ec911cbea87081431e20ef3019a/fingerprint2.js](https://raw.githubusercontent.com/fingerprintjs/fingerprintjs/5019fb8c4b3a1ec911cbea87081431e20ef3019a/fingerprint2.js). I'll wait for your message before releasing the fix to NPM.

**Comment by Valve** [comment]
@Finesse you probably meant to mention @BafS , not yourself

**Comment by Finesse** [comment]
> @Finesse you probably meant to mention @BafS , not yourself

@Valve You are right

**Comment by Finesse** [comment]
@BafS A kind reminder:

> I'll wait for your message before releasing the fix to NPM
