### ISSUE TITLE
Delete this fucking privacy violation

### ISSUE THREAD

**Issue by skidus** [fingerprintjs/fingerprintjs#613]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
- What device and browser are you using?
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by Finesse** [comment]
HI @skidus. This topic is discussed at https://github.com/fingerprintjs/fingerprintjs/issues/430. Please read the thread and leave arguments for your opinion.

Since this issue is a duplicate and provides no discussable information, I'm closing it.
