### ISSUE TITLE
Fingerprintjs Pro effectiveness on the Brave browser

### ISSUE THREAD

**Issue by joecoker** [fingerprintjs/fingerprintjs#614]
The documentation states that FingerprintJS Pro is effective at fingerprinting the Brave internet browser. My understanding is that the technical demo displayed on the fingerprintJS home page uses the Pro service.

However, the demo does not return the same ID between different browsing sessions using the Brave browser when the cookies have been cleared in between.

Below are the two Ids I received from the technical demo.

**1st visit**
![id1](https://user-images.githubusercontent.com/38155802/108415476-82dfe600-7225-11eb-9575-ef699007e085.png)

**2nd visit after clearing the cookie data and restarting the browser**
![id2](https://user-images.githubusercontent.com/38155802/108415480-83787c80-7225-11eb-91fd-a7628c01014a.png)

How effective is the pro version at fingerprinting the Brave browser?

**Comment by Finesse** [comment]
FingerprintJS Pro is a separate product. Please contact support@fingerprintjs.com for a FingerprintJS Pro support.
