### ISSUE TITLE
extracting canvas data because no user input was detected.

### ISSUE THREAD

**Issue by yarekc** [fingerprintjs/fingerprintjs#615]
Using TOR, seems that library is not efficient: 

**The fingerprint changes all the time**: it looks like the canvas trick is blocked by TOR.
Any idea on how to have a more reliable result ?

`Blocked ****  from extracting canvas data because no user input was detected.`

**Comment by Valve** [comment]
@yarekc thanks for your information.
Our library does not support Tor browsers.
Please see the list of supported browsers here: https://github.com/fingerprintjs/fingerprintjs#browser-support

Closing the issue, please feel free to reopen with additional questions or comments.

**Comment by yarekc** [comment]
ok, but what about the PRO version ?
Does it work fine with TOR ?
Regards

**Comment by Valve** [comment]
@yarekc pro version does not support Tor version either. 
I don't have data about the accuracy of Pro on Tor, I assume it's higher than with the OSS version, but how much higher - we don't know, because we never targeted Tor specifically.
