### ISSUE TITLE
Question about component

### ISSUE THREAD

**Issue by MaximeFrancoeur** [fingerprintjs/fingerprintjs#617]
How can we turn off or remove component? (Like Canvas)

**Comment by Finesse** [comment]
Please try this solution: https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md#customization. Does it help?

**Comment by MaximeFrancoeur** [comment]
if we exclut canvas and font this can corrupt the HEX and at the same time bytes?
Because after exclude these components we have weird behavior to save visitorID inside Bigtable.

**Comment by Finesse** [comment]
@MaximeFrancoeur What do you mean saying “corrupt the HEX and bytes”? Could you please show an example? You would get a valid hex string with a constant length regardless of the fingerprint components that you exclude and include.

**Comment by MaximeFrancoeur** [comment]
After investigation it's seem like another thing who corrupt the hex. Thanks for your answer.
