### ISSUE TITLE
Demo page has incorrect basic ip information

### ISSUE THREAD

**Issue by andrewdavidcostello** [fingerprintjs/fingerprintjs#619]
### Scenario

- **What's the scenario, what happens and what did you expect to happen?**
Went to the demo page and expected a location near to my house, instead I received a location somewhere in the southeast of England instead of Scotland. Other IP lookup providers give a more accurate reading from IP data within the region of the same city/town.

Apologies if this isn't the right place but we were looking to evaluate your product however other IP providers give a location for a landline internet connection to be within the same city whereas fingerprintjs gives a result that is way off which would mean using another ip lookup service on top of this given there wouldn't be any confidence in the data. Is this just an issue with IPs in general with your library/service that they are not accurate outside of the US?

- **What device and browser are you using?**
Mac, Safari, Chrome

- **What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)**
Whatever is on the demo page currently.

### Fingerprint data
N/A

**Comment by Valve** [comment]
Hi @andrewdavidcostello 

Thanks for your message. 
Our main API is for browser identification; the IP lookup is secondary and is only shown for informational purposes. Our API works w/out IP information and returns back a `visitorId` value.

We don't try to achieve or maintain high IP resolution accuracy.

Please also note that GitHub issues are only for the open source JavaScript library, called fingerprintjs, 
the demo page that you referred to is for our professional, paid service, called FingerprintJS Pro.
For all pro-related questions, please contact support@fingerprintjs.com
I'm closing this issue, please feel free to reopen with additional questions or feedback.
