### ISSUE TITLE
Total Blocking Time is being increased by over 400ms after implementing Fingerprint

### ISSUE THREAD

**Issue by elemarin** [fingerprintjs/fingerprintjs#623]
### Scenario

Hi, 

We've recently started using Fingerprintjs for user detection, and we've noticed a big increase in the total CPU blocking time after the implementation.

This metric is important because it can affect the [First Input Delay](https://web.dev/fid/) which is now part of the [Core Web Vitals](https://web.dev/vitals/) metrics by google.

This can have a severely impact on SEO ranking, since the Core Web Vital metrics are now a ranking factor for Google .

### Fingerprint data

I've created a github repository to reproduce this, you can see it [here](https://github.com/elemarin/fingerprint-demo), using the sample implementation given in the instructions.

I've hosted 2 versions of the same page, one using fingerprint to generate a visitor Id, and other that just generates a random GUID.

**Random GUID**: 
URL: https://elemarin.github.io/fingerprint-demo/nofp.html
webpagetest URL:

![image](https://user-images.githubusercontent.com/987341/110733889-60ba0200-81ec-11eb-8f7c-4ea9ed005164.png)

**Fingerprint**: 
URL: https://elemarin.github.io/fingerprint-demo/fp.html
webpagetest URL: https://webpagetest.org/result/210311_AiK5_44f782f946a121e3957b258d31f075f4/
![image](https://user-images.githubusercontent.com/987341/110733938-76c7c280-81ec-11eb-9d06-c034c20db9c1.png)

**Comment by Finesse** [comment]
Hi Esteban, I appreciate the effort you've put into this issue, thank you. Unfortunately, getting a fingerprint requires a noticeable CPU work, and there will be more work when we add new entropy sources. What you can do is to delay calling `fp.get()`, preferable to the moment when you really need a fingerprint, for example, when a sign up/in button is about to be clicked.

<details>
<summary>A synthetic example for Lighthouse</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fingerprint</title>
</head>
<body>
    <h1>This page contains fingerprint</h1>
    <p class="text">This is my Fingerprint ID: </p>

    <a href="index.html">Back home!</a>
    <script>
        function initFingerprintJS() {
          FingerprintJS.load()
            // Wait in order no to include the fingerprinting into the page initial load time
            .then(fp => new Promise(resolve => setTimeout(resolve, 5000, fp)))
            // The FingerprintJS agent is ready.
            // Get a visitor identifier when you'd like to.
            .then(fp => fp.get())
            .then(result => {
              // This is the visitor identifier:
              const visitorId = result.visitorId;
              let text = document.querySelector('.text');

              text.textContent += visitorId;
            });
        }
      </script>
      <script
        async
        src="https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js"
        onload="initFingerprintJS()"
      ></script>
</body>
</html>
```

</details>

<details>
<summary>A more true to life example</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fingerprint</title>
</head>
<body>
    <h1>This page contains fingerprint</h1>
    <button class="signup" disabled>Sign up</button>
    <p class="text">This is my Fingerprint ID: </p>

    <a href="index.html">Back home!</a>
    <script>
        function initFingerprintJS() {
          const signUpButton = document.querySelector('.signup');
          signUpButton.disabled = false;
          const fpLoadPromise = FingerprintJS.load();

          signUpButton.addEventListener('mouseover', () => {
            fpLoadPromise
              .then(fp => fp.get())
              .then(result => {
                // This is the visitor identifier:
                const visitorId = result.visitorId;
                let text = document.querySelector('.text');

                text.textContent += visitorId;
              });
          }, { once: true });
        }
      </script>
      <script
        async
        src="https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js"
        onload="initFingerprintJS()"
      ></script>
</body>
</html>
```

</details>

**Comment by Finesse** [comment]
@elemarin Let me know if it solves your problem

**Comment by Finesse** [comment]
Closing due to the lack of response
