### ISSUE TITLE
Fonts source changes the look of the page

### ISSUE THREAD

**Issue by sajiniho** [fingerprintjs/fingerprintjs#628]
version: Fingerprintjs2 2.1.0
device: every android os
browser: samsung internet browser, latest version

this "var createSpan = function () { "
create an elment with styles that not supported in told browser and caused to jump top of the page when the page has a scroll.

I changed the styles from:
      s.style.position = 'absolute'
      s.style.left = '-9999px'
      s.style.fontSize = testSize

to :
      s.style.position = 'absolute'
      s.style.visibility = 'hidden'
      s.style.overflow = 'hidden'
      s.style.top = '0px'
      s.style.height = '1px'
      s.style.width = '1px'
      s.style.padding = '0px'
      s.style.border = '0px'
      s.style.margin = '0px'
      s.style.fontSize = testSize

* I'm not sure this is a good way or not but thats worked.
* what do you think?

**Comment by Finesse** [comment]
These CSS rules are so old that they are supported on all devices that accept the today's SSL certificates. Probably, your page CSS interferes the fingerprinting process. Could you please provide a page where I can reproduce the problem?

**Comment by Finesse** [comment]
Probably, related to https://github.com/fingerprintjs/fingerprintjs/issues/592 (page CSS affects the fonts entropy source)

**Comment by sajiniho** [comment]
you must login to website.
https://www.monta.ir
send me a message to write back a username and pass. 
sajadkamali017@gmail.com

**Comment by Finesse** [comment]
@sajiniho I'll make a more robust implementation of the fonts source. For now, please make sure that you page styles don't interfere with divs and spans created by FingerprintJS (they are appended to the end of the `<body />`).

**Comment by Finesse** [comment]
The fix will be published in the next patch release
