### ISSUE TITLE
You can no longer pass in options to exclude components in latest version of library

### ISSUE THREAD

**Issue by swilliams-a3digital** [fingerprintjs/fingerprintjs#633]
### I expected to be able to pass in exclude components they way you could in previous versions
e.g.
let options = { excludeSources: { 'availableScreenResolution': true }};
            fp.get(<any> options).then(result => {

**Comment by Finesse** [comment]
Could you please explain why you need to exclude components? If we understand your needs, we'll probably offer a better solution.

Related to https://github.com/fingerprintjs/fingerprintjs/issues/590

**Comment by swilliams-a3digital** [comment]
We'd like to disable / remove the availableScreenResolution as factor, because the value is inconsistent, and it causes the device id to frequently change.

**Comment by Finesse** [comment]
@swilliams-a3digital You can do it. See this guide: https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md#customization. Does it solve your issue?

**Comment by swilliams-a3digital** [comment]
I took a look but I don't see how to disable  available screen resolution as a factor in creating the fingerprint.

**Comment by Finesse** [comment]
Try this:

```js
// ...
const result = await fp.get()
const { availableScreenResolution, ...components } = result.components
const visitorId = FingerprintJS.hashComponents(components) // Use this id instead of result.visitorId
```

**Comment by Finesse** [comment]
Closing due to the lack of response. The [extending](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) guide shows how to remove a component.

**Comment by cxytomo** [comment]
the problem is `components` no longer meets the ts type validation of `UnknownComponents`
`export function hashComponents(components: UnknownComponents): string {
  return x64hash128(componentsToCanonicalString(components))
}`

**Comment by Finesse** [comment]
@cxytomo Please give a full reproducible code example

**Comment by cxytomo** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/2089688/165892556-875056e4-8ccd-445b-b0a2-9a5a9f8c6d0a.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2089688/165892733-6de31853-c005-4030-bbc6-5beb4b5cbbe2.png">
<img width="726" alt="image" src="https://user-images.githubusercontent.com/2089688/165892768-39bcae2f-a566-43ea-ab1e-9a8a96f6ba74.png">
othercomponents seems no longer meets the type validation of `UnknownComponents`
