### ISSUE TITLE
Improve extend components scenario in docs

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#636]
Please consider improving main readme API docs section that talks about removing or adding components. This is a relatively frequent source of confusion.
Probably we should move this section: https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md#customization
into a dedicated page in /docs and then link to that page from the API section that talks about extending components.

**Comment by Finesse** [comment]
Closed by #637
