### ISSUE TITLE
HDR check should support non-Safari browsers

### ISSUE THREAD

**Issue by eligrey** [fingerprintjs/fingerprintjs#652]
I noticed a flaw in your HDR detection logic.

Chrome doesn't support the `dynamic-range` media query [as used by FingerprintJS in hdr.ts](https://github.com/fingerprintjs/fingerprintjs/blob/d1c3ccf0b29f8753c9c9e71b487567c14b66f9c8/src/sources/hdr.ts). Fortunately, Chrome does support the `color-gamut` media query. A better cross-browser implementation is as follows:

```js
matchMedia('(dynamic-range: high), (color-gamut: p3)').matches
```

This media query correctly returns `true` when Chrome is open on my HDR display on Mac OS and Windows.

### Scenario

- What's the scenario, what happens and what did you expect to happen? I expected FingerprintJS to detect HDR support in Chrome.
- What device and browser are you using? Chrome on a device with HDR displays
- What version of fingerprintjs exhibits this issue? All versions, including latest master (3.1.0)

### Fingerprint data

n/a

**Comment by Finesse** [comment]
There is [an entropy source](https://github.com/fingerprintjs/fingerprintjs/blob/master/src/sources/color_gamut.ts) that checks the `color-gamut` already. FingerprintJS doesn't aim to detect HDR support, it aims to get visitor entropy. Adding the check that you suggest will make the library more complex, and will increase neither library's entropy nor stability. Therefore, we won't implement your suggestion, sorry.

**Comment by eligrey** [comment]
Afaik color depth doesn't specifically have to correlate to a display's ability to display the P3 color space. Understandable if you want to keep this close.

I don't think `color-gamut: p3` is technically equivalent to `screen.colorDepth >= 30`.
