### ISSUE TITLE
different fingerprints from same browser & same codebase on different servers

### ISSUE THREAD

**Issue by dpalic** [fingerprintjs/fingerprintjs#660]
### Scenario

- What causes the fingerprint to change?

using the exactly same code on two webservers results into different fingerprints. One from localhost apache, one from remote apache.

Localhost is providing the same fingerprint as the paste.aes.pm link. 
The remote apache version is generating a totally different fingerprint

With chromium I am getting also two different fingerprints

I cannot reproduce this issue on Firefox. Here I get twice the same fingerprint

- What device and browser are you using?

linux, ubuntu 18.04
chrome 90.0

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment)

3.1.2

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.

https://paste.aes.pm/?a760f289f84b6c8b#E3suongdsy43p2R4vnZ7TorEJLxBab3GPkxmxyg5hsX7

Is it an issue on my side with the configuration, that I am getting different fingerprints?

**Comment by Finesse** [comment]
@dpalic It's ok that HTTP and HTTPS pages produce different fingerprints. Could you please try your pages with the same protocol (both HTTP or both HTTPS) and tell if the fingerprints are the same?

**Comment by dpalic** [comment]
@Finesse they are http both

urls are
http://localhost/Fingerprint/v2/
http://publicDns/Fingerprint/v2/

**Comment by Finesse** [comment]
Could you please share fingerprint [debug](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/api.md#agentget-debug-boolean--promiseobject) data for both of the pages so that I can see the difference?

**Comment by dpalic** [comment]
maybe stupid question, could not find a doc reference. How to enable debug on my side?

**Comment by Finesse** [comment]
Add `debug: true` to the `get` options:

```diff
  const fpPromise = FingerprintJS.load()
  const fp = await fpPromise
- const result = await fp.get()
+ const result = await fp.get({ debug: true })
```

The debug data will be printed to the browser console.

**Comment by dpalic** [comment]
here we go: https://www.dropbox.com/sh/n2prrbiryo1mvtk/AADAa3ZbNaSofh3Pk_PXXrB8a?dl=0

it looks like it is always the duration value

**Comment by Finesse** [comment]
Thank you! The durations don't affect `visitorId`. The only difference in your examples is `deviceMemory`. [deviceMemory](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory) is available only in secure context, and localhost is considered as secure context by Chrome. So, your fingerprint difference is caused by different page contexts. If all your pages are served via HTTP and none of them via localhost or all via HTTPS, the fingerprints will be the same, otherwise they may differ. Does this information solve your issue?

**Comment by dpalic** [comment]
okay thank you!
I have checked if I can contriubte this question to FAQ. But FAQ seems to unavailable.
Maybe a good question for a FAQ to answer there? (https, http and localhost as secure contexts)
e.g. 
_Why do my fingerprints differ on same browser but different webservers?_

**Comment by Finesse** [comment]
What FAQ do you mean? You can post a question to the [discussions](https://github.com/fingerprintjs/fingerprintjs/discussions/categories/q-a) and I'll answer it

**Comment by Finesse** [comment]
Closing because of the lack of response

**Comment by shoyuf** [comment]
> What FAQ do you mean? You can post a question to the [discussions](https://github.com/fingerprintjs/fingerprintjs/discussions/categories/q-a) and I'll answer it

What he means is that we need to have a FAQ module in the documentation about these common questions

**Comment by Valve** [comment]
@shoyuf I don't think this is a common question, I personally see this question for the first time. It might be difficult for us to anticipate other questions like that so a better way is to just ask in discussions and we'll try to answer.
Thanks
