### ISSUE TITLE
Impact of User Agent reduction

### ISSUE THREAD

**Issue by sandrolain** [fingerprintjs/fingerprintjs#661]
Hello,
the Blink / Chromium team has recently released an official communication with timeline details on the reduction of the User-Agent:

- [https://groups.google.com/a/chromium.org/g/blink-dev/c/e3pZJu96g6c](https://groups.google.com/a/chromium.org/g/blink-dev/c/e3pZJu96g6c)
- [https://www.chromium.org/updates/ua-reduction](https://www.chromium.org/updates/ua-reduction)

Can and how can this change affect the fingerprint calculation?
Are there any plans to switch to the new API (navigator.userAgentData)?

**Comment by Finesse** [comment]
FingerprintJS doesn't use user-agent because many browsers can or do fake it. Therefore, the reduction of the User-Agent won't affect FingerprintJS at all.

**Comment by sandrolain** [comment]
Thanks for the reply.  Does this apply to both version 3 and version 2?

**Comment by Finesse** [comment]
It applies to version 3 only.

Version 2 uses user-agent, but the user-agent reduction will break nothing, it will only reduce the entropy. Chrome will freeze user-agent, therefore the code relying to user-agent will continue working. Version 2 is feature-locked, so we won't do changes related to the user-agent reduction.
