### ISSUE TITLE
Throwing InvalidStateError

### ISSUE THREAD

**Issue by rittme** [fingerprintjs/fingerprintjs#672]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
When running get(), sometimes the following error is thrown:
```
InvalidStateError: Failed to execute 'startRendering' on 'OfflineAudioContext': cannot startRendering when an OfflineAudioContext is closed
  at a(./node_modules/@fingerprintjs/fingerprintjs/dist/fp.esm.js:629:21)
```
The referenced line is this one: https://github.com/fingerprintjs/fingerprintjs/blob/7096a5589af495f1f46067963e13ad27d887d185/src/sources/audio.ts#L86

- What device and browser are you using?
The error seems to occasionally happen on Chrome browser > 86.

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
v3.1.2
### Fingerprint data

Not applicable

**Comment by Finesse** [comment]
Hi @rittme, thank you for letting us know.

Where do you see the error? Is it printed to browser console or returned in the list of components (`(await fp.get()).components.audio.error`)?

Do you notice something suspicious in users that experience this error (e.g. same IP subnet that belongs to a cloud)?

Do you know if this error happens only when the page is unloading (getting closed)?

**Comment by rittme** [comment]
Hi @Finesse, 

> Where do you see the error? Is it printed to browser console or returned in the list of components ((await fp.get()).components.audio.error)?

this error is thrown on the browser console (more specifically, logged on sentry server).

> Do you notice something suspicious in the users that experience this error (e.g. same IP subnet that belongs to a cloud)?

Nothing suspicious, quite homogeneous range of IP addresses and access patterns. 

>Do you know if this error happens only when the page is unloading (getting closed)?

I don't know that as I can't reproduce it. 

Catching this error and returning it in the list of components instead of throwing would probably solve this issue.

**Comment by Finesse** [comment]
Thank you for the information. Could you please provide a list of user agents that experience this error? I was never able to reproduce it, I want to find why it happens.

> Catching this error and returning it in the list of components instead of throwing would probably solve this issue.

It's implemented in v3.2.0. Could you please update and try it?

**Comment by rittme** [comment]
>Could you please provide a list of user agents that experience this error? I was never able to reproduce it, I want to find why it happens.
They are all recent versions of Chrome. Some examples:
```
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
```

> It's implemented in v3.2.0. Could you please update and try it?
I will try it out, thank you!

**Comment by Finesse** [comment]
@rittme Have you tried it? What's the result?

**Comment by rittme** [comment]
Hey @Finesse, yes, I tried it out. 
The error is fixed! Thank you for the help!

**Comment by Finesse** [comment]
@rittme Thank you too!

**Comment by jyyang42** [comment]
Hi @Finesse seeing the same error here, and I'm on 3.3.0.
Some samples of user agents that throw the errors are:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Mozilla/5.0 (Windows NT 5.1; rv:52.9) Gecko/20100101 Goanna/3.4 Firefox/52.9 PaleMoon/27.6.2
Mozilla/5.0 (Linux; Android 8.1.0; K503) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 YaBrowser/21.5.3.740 Yowser/2.5 Safari/537.36
```
Service Worker state is redundant error
```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
Mozilla/5.0 (iPod touch; CPU iPhone OS 12_5_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
```

**Comment by Finesse** [comment]
@jyyang42 Where do you see the error? Is it printed to browser console or returned in the list of components (`(await fp.get()).components.audio.error`) or thrown from `fp.get()`?

**Comment by jyyang42** [comment]
> @jyyang42 Where do you see the error? Is it printed to browser console or returned in the list of components (`(await fp.get()).components.audio.error`) or thrown from `fp.get()`?

@Finesse , it's thrown in the browser and shows up in the console.

**Comment by Finesse** [comment]
> it's thrown in the browser

@jyyang42 What exactly do you mean?

**Comment by jyyang42** [comment]
@Finesse printed to browser console

**Comment by Finesse** [comment]
@jyyang42 It's impossible for FingerprintJS v3.3.0 or newer to produce an `InvalidStateError: Failed to execute 'startRendering' on 'OfflineAudioContext': cannot startRendering when an OfflineAudioContext is closed` console message. All the errors produced by `context.startRendering()` are caught and saved into the `components.audio.error` field of the `get()` result.

Could you please check it once again? Maybe, you have an old library version running together with a new version, or another script produces the error.

**Comment by danielstorch** [comment]
Hey @Finesse, we are using fingerprintjs version 3.3.3 and we are still seeing this in the browser console/sentry. As i can see from sentry, it is caught by the the `onunhandledrejection` method. There are a bunch of different user agents reporting this error.

Here are some example user agents:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

**Comment by Finesse** [comment]
@danielstorch Could you please check that stacktrace and make sure the error is produced inside the FingerprintJS code

**Comment by danielstorch** [comment]
@Finesse Sorry, i don't have any stacktrace available. If the error occurs again, i will comment here.

**Comment by danielstorch** [comment]
@Finesse We again see this error. This time the code snippet where it happens was logged:
```
{snip} ath.min(500,a+5e3-Date.now()))},u=function(){try{switch(e.startRendering(),e.state){case"running":a=Date.now(),i&&s();break;case"suspended": {snip}
```

**Comment by Finesse** [comment]
@danielstorch Do you know whether the `get()` promise is rejected or the entropy source emits an error in this case? If the entropy source fails, you'll see something like this in the result object:

```js
{
  "visitorId": "abc",
  "components": {
    // ...
    "audio": {
      "error": "InvalidStateError: Failed to execute 'startRendering'...",
      "duration": "33"
    }
    // ...
  }
}
```

**Comment by danielstorch** [comment]
@Finesse unfortunately I do not know that. We currently only care about the fingerprint in the result object and sentry only logs this error above. 
Soon we will improve our logging and also submit the components. If this is implemented and it happens again, i will comment here. For now i don't have further information

**Comment by danielstorch** [comment]
@Finesse We have now started logging a bit more. Here are the results:

In the last 24 hours 5 browsers/users had this error reported to sentry. But in all 5 cases the fingerprint was calculated and the audio source was available. No error was submitted in any of the components from fingerprint. So it seems to be something that happens after the fingerprint and components/sources where calculated?

Additionally we are now also logging any "component error" if fingerprint reports it. Until now those where all "audio errors", where the audio value could not be calculated. Here are the two errors we are currently seeing:
```
1: Cannot find function createOscillator in object [object OfflineAudioContext].
2: e.getChannelData(...).subarray is not a function
```

I hope this helps.

**Comment by Finesse** [comment]
@danielstorch Thank you for the information, it seems to be helpful

> So it seems to be something that happens after the fingerprint and components/sources were calculated?

This is what I suspect

Sorry for not responding for a long time. This issue is on my to-do list, I didn't have enough time to get to it.
