### ISSUE TITLE
fingerprintjs got different id in same browser while using different url visiting the same server

### ISSUE THREAD

**Issue by yaohwu** [fingerprintjs/fingerprintjs#682]
fingerprintjs got different id in same browser while using different url visiting the same server

### Scenario Q&A

- What causes the fingerprint to change?

  A: When visiting same server by different url，such as http://127.0.0.1/app/index.html and http://192.168.1.100/app/index.html

- What device and browser are you using?

  A: Chrome [91.0.4472.114 (x86_64)] and other browsers like edge and firefox.

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment)

   A: [3.2.0](https://github.com/fingerprintjs/fingerprintjs/releases/tag/v3.2.0)

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

here are two debug files, 127.txt for http://127.0.0.1/app/index.html, 192.txt for http://192.168.1.100/app/index.html.

[127.txt](https://github.com/fingerprintjs/fingerprintjs/files/6807379/127.txt)
[192.txt](https://github.com/fingerprintjs/fingerprintjs/files/6807378/192.txt)

**Comment by yaohwu** [comment]
it works well in safari.

**Comment by makma** [comment]
Hi @yaohwu , thank you for your question, I quickly diffed your debug txts and the only difference I found was the `deviceMemory` signal. In your Safari example, the `navigator.deviceMemory` [is not supported in Safari](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory#browser_compatibility) therefore browser's API returns a stable signal. 

Other than that, [from the docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory):

> This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.

Can you run both your servers with HTTPS and check the results again?

**Comment by yaohwu** [comment]
@makma thanks for your reply. The debug files was generated by Chrome not Safari. In other words, Chrome uses different `navigator.deviceMemory` only because of visiting same server through different ip, does it?

**Comment by makma** [comment]
Yes, I was aware of the Safari use case.

> Chrome uses different navigator.deviceMemory only because of visiting same server through different ip, does it?

No, the reason is because of using different in/secure environments. You probably use HTTPS on 127... and HTTP on 192... servers, therefore the different signals and different fingerprints.
This is a known behavior and actually a feature of the FingerprintJS. We consider adding this to the docs.

**Comment by yaohwu** [comment]
> You can learn more about secure context in the MDN documentation.

Yes, chrome must consider http://127.0.0.1 as a secure context.

**Comment by makma** [comment]
No you are not, but Chrome threats it like a secure environment.
```
“Secure origins” are origins that match at least one of the following (scheme, host, port) patterns: 
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 
```
Source: http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

**Comment by yaohwu** [comment]
Ok, I got the reason. Thank you.
