### ISSUE TITLE
Does not work in Firefox extension

### ISSUE THREAD

**Issue by rahulbaid** [fingerprintjs/fingerprintjs#683]
Browser: Firefox Developer Edition
Version: 91.0beta
Error: `'requestIdleCallback' called on an object that does not implement interface Window`
Image shown below.

<img width="1392" alt="Screenshot 2021-07-15 at 10 32 13 PM" src="https://user-images.githubusercontent.com/87349565/125805745-93aa1ddb-921a-447d-8bac-f107ef737da8.png">

**Comment by makma** [comment]
Hello @rahulbaid, I've just tried our [example](https://fingerprintjs.github.io/fingerprintjs/) on the mentioned beta Firefox and it works just fine for me. Please, attach steps to reproduce. Thank you.
Cheers! 🎉

**Comment by rahulbaid** [comment]
Hi @makma,

Steps to reproduce:
1. Clone the [repo](https://github.com/duo-labs/chrome-extension-boilerplate). 
2. In the content script, add the code below
`import FingerprintJS from '@fingerprintjs/fingerprintjs'

// Initialize an agent at application startup.
const fpPromise = FingerprintJS.load()

;(async () => {
  // Get the visitor identifier when you need it.
  const fp = await fpPromise
  const result = await fp.get()

  // This is the visitor identifier:
  const visitorId = result.visitorId
  console.log(visitorId)
})()`
3. Then load the extension in Firefox.

I am trying to basically run the script on on every page load. It works on Chrome but gives an error in Firefox.

**Comment by Finesse** [comment]
Related issues:

- https://github.com/facebook/react/issues/16606
- https://github.com/taye/interact.js/pull/810, https://discourse.mozilla.org/t/typeerror-cancelanimationframe-called-on-an-object-that-does-not-implement-interface-window/58386

We will fix it in a future release.

You can fix the issue now by adding the following line before calling `FingerprintJS.load()`:

```js
window.requestIdleCallback = window.requestIdleCallback.bind(window)
```

**Comment by rahulbaid** [comment]
Thank you @Finesse

**Comment by Finesse** [comment]
The fix will be published in the next release
