### ISSUE TITLE
TypeError in getCurrentScreenFrame: can't access dead object

### ISSUE THREAD

**Issue by timhwang21** [fingerprintjs/fingerprintjs#691]
### Scenario

- What's the scenario, what happens and what did you expect to happen?

On Firefox (and only Firefox), `getCurrentScreenFrame` [errors on this line](https://github.com/fingerprintjs/fingerprintjs/blob/8552bfb7c800bf4f015e30bbb1c341dabac47730/src/sources/screen_frame.ts#L113).

- What device and browser are you using?

We are seeing this issue for Firefox 68-now (probably accesses more) and Firefox Mobile.

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

2.1.5, but I believe the issue still appears on master.

### Fingerprint data

Not applicable

The root cause is that Firefox has a security feature that prevents keeping strong refs to DOM objects that have been removed from the screen. [More information here.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object)

I believe the fix would be to ensure `s` (and other references to DOM nodes) are first checked with `Components.utils.isDeadWrapper(s)`, and early exiting if so.

If it helps, I can work on a PR maybe next weekend or so. Thanks!

**Comment by Finesse** [comment]
Hi @timhwang21. I've checked FingerprintJS in various versions of Firefox on BrowserStack, I've faced no errors. Could you please give more specific steps to reproduce the error?

There is a discrepancy in your message. You say that you use FingerprintJS v2.1.5 but give a link to a source code of version 3. Also the code that you've mentioned operates no DOM nodes.

**Comment by timhwang21** [comment]
> There is a discrepancy in your message. You say that you use FingerprintJS v2.1.5 but give a link to a source code of version 3.

I should have linked the v2.1.5 source, that's my mistake. But the line in question is essentially identical. 

> Also the code that you've mentioned operates no DOM nodes.

`screen` is a property on `window` which is the DOM object in question, I believe. 

As for reproduction, I will double check, but the steps are something like:

1. Our code loads in an iframe
2. Promise or timeout lines up `getScreenFrame` to be called (several code paths do this)
3. iframe is removed from DOM
4. `getScreenFrame` is called; tries to access property of `window` but the window object is apparently dead

**Comment by Finesse** [comment]
Do you mean that FingerprintJS runs in an iframe, the iframe is removed while FingerprintJS is running, and the error occurs after the iframe is removed? If so, I'm afraid that it's not a FingerprintJS's fault because any code can fail in such conditions. Even if FingerprintJS catches the error and continues, it won't be able to get the visitor id, so it makes no sense to handle the error. What I can advice:

- Make sure the iframe doesn't get removed until FingerprintJS completes

    ```js
    const fp = await iframe.contentWindow.FingerprintJS.load()
    const result = await fp.get()
    iframe.remove()
    ```
- If you don't control the iframe, the catch the error

    ```js
    try {
      const fp = await iframe.contentWindow.FingerprintJS.load()
      const result = await fp.get()
    } catch (error) {
      // Handle error
    }
    ```
- Run FingerprintJS not in the iframe

**Comment by Finesse** [comment]
@timhwang21 Have you solved your issue?

**Comment by timhwang21** [comment]
No, but I think I can handle it independently of the library.
