### ISSUE TITLE
Does checking the fingerprint prevent Googlebot from crawling my website?

### ISSUE THREAD

**Issue by tqdo** [fingerprintjs/fingerprintjs#693]
I wonder whether checking the fingerprint prevents Googlebot from crawling my website? Because it is likely that Googlebot has the same fingerprint everytime it crawls websites.

**Comment by makma** [comment]
Hi @tqdo, what do you mean by 

> checking the fingerprint

? There's no reason why this repository should cause excluding your page from indexing (we are not tampering with meta tags). It's possible the bot has the same fingerprint hash every time it crawls the website.

**Comment by makma** [comment]
I’m closing this issue now because of inactivity.

@tqdo we can always reopen it though! :) Please update the issue if needed.
