### ISSUE TITLE
fingerprint has changed on different servers

### ISSUE THREAD

**Issue by jackiehamchen** [fingerprintjs/fingerprintjs#698]
### Scenario

- What causes the fingerprint to change?
I deployed fingerprintjs on a linux server to print the visitorId on my Chrome browser and i got a visitorId, but i got a different visitorId when i run this fingerprintjs locally (MacOS) using the same Chrome browser.
- What device and browser are you using?
MacOS, Chrome (Version 93.0)
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment)
Version 3.3.0

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by Finesse** [comment]
Hi @jackiehamchen! Do you mean that you get different visitor ids when you run FingerprintJS on different servers (local and remote)? If yes, please check whether both the servers have secure or both have insecure context (`window.isSecureContext`). FingerprintJS is expected to produce different ids in different contexts. A similar issue: https://github.com/fingerprintjs/fingerprintjs/issues/682.

**Comment by Finesse** [comment]
Closing due to the lack of response
