### ISSUE TITLE
Incorrect documentation for font detection

### ISSUE THREAD

**Issue by ankurparihar** [fingerprintjs/fingerprintjs#714]
### Scenario

- I have been reading how fonts are detected in fingerprintjs. I saw this comment https://github.com/fingerprintjs/fingerprintjs/blob/aa7ab5d41dd44ed1bd75fce56c1f2c688cb2c8a3/src/sources/fonts.ts#L10-L11 
- But If we think of it, if it doesn't match all 3 that means that the test string render with some other font, which suggests that the requested font is successfully loaded from OS and thus indeed available.
- On the other hand, looking at the code, I found that code is checking it this way, which is correct https://github.com/fingerprintjs/fingerprintjs/blob/aa7ab5d41dd44ed1bd75fce56c1f2c688cb2c8a3/src/sources/fonts.ts#L120-L127
- > If for some default font, the dimensions doesn't match, that means font is available.

- Browser: Not applicable for this issue
- On the master branch

**Comment by Finesse** [comment]
You are right, thank you
