### ISSUE TITLE
make ad-dom blockers look safer in some web security detectors

### ISSUE THREAD

**Issue by yaohwu** [fingerprintjs/fingerprintjs#734]
The feature, using ad-blocker component to generate fingerprint, is a fantastic idea.
https://fingerprintjs.com/blog/ad-blocker-fingerprinting/

But some web security detectors treat  ad-blocker filtering rules as unsafe web links.
Although such detect results are not credible, I have to do some work to make it look safer.
https://github.com/fingerprintjs/fingerprintjs/compare/v3.2.0...yaohwu:strict-web-security-v3.2.0?expand=1

Would that kind of thing be considered in the code of fingerprintjs?

**Comment by makma** [comment]
Hi @yaohwu !
Thank you for the suggestion and your interest. Honestly, I'm not sure, I believe the author had reason not to add it to the library. My guess is it was quite unreliable. What's your opinion @Finesse?

**Comment by Finesse** [comment]
Hi @yaohwu. We've never faced such feedback before. Could you please provide links to or the names of the security detectors? The change introduces some difficulties in the maintenance process (the list of ad blocking filters is updated periodically), so I want to make sure that the change is worth the difficulties or find for a better solution.

P.S. Your code reimplements the built-in [atob](https://developer.mozilla.org/en-US/docs/Web/API/atob) and [btoa](https://developer.mozilla.org/en-US/docs/Web/API/btoa) functions.

**Comment by yaohwu** [comment]
> Your code reimplements the built-in atob and btoa functions. For unicode characters, one can use a simple transformation because the goal is obfuscating the original string (not making an actual base-64 string).

Thank you for your code advice.

The web security-detect service is provided by a cloud provider named [天翼云](https://www.ctclouds.com/) in China. If the web page static resources appear content like 'a[href*="//playdsb. com/ke"]', the service will report unsafe messages. The website [playdsb.com](http://playdsb.com) is illegal in China. 

I also think this report is not credible, but I have to fix it. 
There are so many websites using [天翼云](https://www.ctclouds.com/) or other cloud providers in China.
And most of these cloud providers in China provide similar static resource security detection services.
Maybe adding one step generating dom-block-filters in CI/CD flow is a solution.

**Comment by Finesse** [comment]
Thank you for the information. We don't think that this issue is important for us at the moment. I'll leave the issue open to collect more feedback and see how important this issue is for other users.

For now I can suggest you using a post-processor to obfuscate the strings with links in the compiled code. Example transformation: `'a[href*="//playdsb. com/ke"]'` → `atob('YVtocmVmKj0iLy9wbGF5ZHNiLiBjb20va2UiXQ==')`. One can use https://www.npmjs.com/package/@rollup/plugin-replace or a simple JS script that rewrites the file.

**Comment by yaohwu** [comment]
@Finesse  OK, thank you for your reply and advice.

**Comment by acs1899** [comment]
I have the same problem
@yaohwu Have you solved this problem?

**Comment by yaohwu** [comment]
> I have the same problem @yaohwu Have you solved this problem?

I wrote an empty dom blocker module instead of [src/sources/dom_blockers.ts](https://github.com/fingerprintjs/fingerprintjs/blob/ff01390e628cf3f9c5caf22b7349513e78ae5d9d/src/sources/dom_blockers.ts)


Just make the new empty dom blocker module function `getDomBlockers` return `undefined`.

Easy but works.

**Comment by acs1899** [comment]
@yaohwu OK, Tks

**Comment by yaohwu** [comment]
> @yaohwu OK, Tks

https://github.com/fingerprintjs/fingerprintjs/commit/7d42dc9183de430acd45e1269da5f2156349843c
