### ISSUE TITLE
Chrome 100 ( User-Agent Reduction Origin Trial and Dates )

### ISSUE THREAD

**Issue by MaximeFrancoeur** [fingerprintjs/fingerprintjs#740]
Hey what is your plan about this -> https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

Did you already made change in FingerprintJS?
Version 3.3.2

![jsfp](https://user-images.githubusercontent.com/5606361/153653281-562489e6-fa28-40e0-a118-f7f773fc0bb8.png)

**Comment by Finesse** [comment]
Hi @MaximeFrancoeur. What exact concern do you have: potential fingerprinting accuracy problems or the issue in the Developer Tools itself?

There is no development version of Chrome 102 yet, so we can't check how FingerprintJS will behave in Chrome 102. FingerprintJS doesn't use user-agent for identification, so the UA reduction won't affect the accuracy.

We will return to this issue when a development version of Chrome 102 is published.

**Comment by MaximeFrancoeur** [comment]
Hi @Finesse I just share the information because I saw in the fingerprintJS few functions use navigator.* function.

**Comment by MaximeFrancoeur** [comment]
@Finesse did you check with Chrome 99?

**Comment by Finesse** [comment]
@MaximeFrancoeur What do you mean I should check in Chrome 99?

As I said, I’m waiting for the release of the development version of Chrome 101 to check the UA reduction.

**Comment by MaximeFrancoeur** [comment]
@Finesse 
Chrome version 101 beta is on beta channel, if you want to test.

**Comment by Finesse** [comment]
@MaximeFrancoeur No sign of UA reduction in desktop Chrome 101 beta, desktop Chrome 102 dev.

Android Chrome 101 beta discloses only the major version in the UA string (which is not a part of the fingerprint). The entropy components aren't changed.

So, no action is required.
