### ISSUE TITLE
What is the best approach to use FingerprintJS

### ISSUE THREAD

**Issue by vietnguyen09** [fingerprintjs/fingerprintjs#747]
Hi guys,

As far as we know, FingerprintJS will generate an ID based on the client's information. And according to the excellent video guide, we can put this ID into a hidden input field, send it to the server, and use this `visitorID` to get the client's info from API.

My question is simple, what if I open developer tools (F12) and change the hidden input value that contains `visistorID`? 
Or using some data changer when posting info to change the `visistorID` such as [THIS ONE](https://chrome.google.com/webstore/detail/tamper-chrome-extension/hifhgpdkfodlpnlmlnmhchnkepplebkb?hl=en)

I thought about encrypting the `visistorID` using CryptoJS when sending this to the server but as far as I know, encrypting something from the client-side is not the best way if we want to hide something.

Any idea?

**Comment by Valve** [comment]
Hi @vietnguyen09 
Thanks for your question 👍🏻 
Can you please create a discussion from it and close this issue as it's not a technical bug of FingerprintJS?
