### ISSUE TITLE
Uncaught (in promise) Error: Subscription not active

### ISSUE THREAD

**Issue by miniyk** [fingerprintjs/fingerprintjs#755]
when i dev mode, also visit localhost,occur;
i use this way to add lib;
![image](https://user-images.githubusercontent.com/5811447/159237923-96bcd706-5042-45de-a70c-8e1203a8b267.png)

this is the error:
![image](https://user-images.githubusercontent.com/5811447/159237636-233784fb-2581-47b2-90c1-893aef3e40c3.png)

note: i register the free pro version

**Comment by makma** [comment]
Hello @miniyk, please, send an email to our official support support@fingerprintjs.com with your subscription identifier. Also, please check (in the dashboard) if your subscription is in the `ap` (Asia) [region](https://dev.fingerprintjs.com/docs/regions).

**Comment by Jamshid5614** [comment]
hi guys, I am also facing the same problem
