### ISSUE TITLE
Same id on different browsers?

### ISSUE THREAD

**Issue by gary00k** [fingerprintjs/fingerprintjs#762]
Hello, I tested demo version of FP Pro and I see a problem. On different browsers, ID is different too. Is there any possibility to identify client device, not only browser?

**Comment by makma** [comment]
Hey @gary00k, for the majority of platforms, FingerprintJS Pro is a browser fingerprinting service. It means it can provide you with a higher granularity (distinguish among various browsers on the same device vs. different devices).

The exceptions might be mobile platforms (native [iOS](https://github.com/fingerprintjs/fingerprintjs-pro-ios), [Android](https://github.com/fingerprintjs/fingerprintjs-pro-android) apps, and [react native](https://github.com/fingerprintjs/fingerprintjs-pro-react-native)).

**Comment by Finesse** [comment]
Closing due to the lack of activity

**Comment by dvf** [comment]
Even on Pro, I get a different id when using Safari and Chrome on the same device. Subdomains have been set up.

Inspecting the payloads, every key is identical except the `userAgent`.

**Comment by makma** [comment]
Hello @dvf,
The `visitorId` (from Fingerprint Pro) and `fingerprint` (from FingerprintJS open source) are browser identifiers (not device identifiers). Therefore different `visitorId`s (or `fingerprint`s) for different browsers on the same device are correct and expected behavior.

**Comment by dvf** [comment]
Thanks for the response @makma, but I'm not sure I understand the sales offering then. All the advertised anti-fraud use cases are not pertinent then, since all someone needs to do to confuse this library is use a different browser.

**Comment by Valve** [comment]
@dvf you can identify any browser on the planet and give it a unique and permanent ID. If someone uses 2 browsers, you'll deal with a collection of two identifiers, but it is still a small collection. Even if an attacker is using multiple browsers, we still deal with a short array of browser IDs, which are easy to iterate, check and compare. 
We reduce the problem space from "we have to deal with unknown" to "we deal with a short collection of browser IDs".
To give you an analogy: any person can legally change their name and any government agency will have to deal with a collection of names for this person, but it's still a known collection. It's incredibly useful and better than just dealing with uncertainty.

**Comment by makma** [comment]
@dvf Another perspective is protecting known and trusted users and putting obstacles in the way of fraudulent users.

To be more specific, let's consider two widespread frauds. Account takeover and credit card fraud. In both, the malicious parties try to use some data that does not belong to them (credentials, credit card data, other personal data, etc...). As an owner of the service (that implemented some kind of protection that utilizes fingerprinting), you had collected sets of browser identifiers associated with a known and legit user. Once an unknown new browser identifier tries to perform a sensitive action on behalf of the known user (e.g. login or product purchase with a credit card), you can detect this suspicious activity and put some barriers (2FA, email verification, temporary account freeze, etc.) between your service and potentially harmful user.

**Comment by dvf** [comment]
Thanks for your detailed responses. Here's what I'm not understanding: why not have the same `visitorId` but different browser identifiers.

It's weird to me to see two almost identical payloads with the only differing field being the `userAgent`. The `visitorId` should be the same with a high confidence score.

**Comment by dvf** [comment]
The use case here is that if a user visits your website, and chooses to download your app, it's easy to do attribution because you know which visit led to which download. I think this would be a major use case for companies considering your Pro offering. Happy to chat more about it.

**Comment by Valve** [comment]
We're working on the multiple browser use case, but thinking about linking browsers together, instead of generating a single ID.
In your example two browsers are very similar, but that's a coincidence, there are a lot of cases where browsers have completely different signals. We want to retain the ability to accurately identify individual browsers but at the same time add the ability to detect that two browsers are related. This way we can maintain the confidence of identification separately from the confidence of linking. Our first area of focus here is various webview to browser and back to webview combinations.
