### ISSUE TITLE
ID lifetime for fingerprint

### ISSUE THREAD

**Issue by kanlancb** [fingerprintjs/fingerprintjs#766]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
   I am a bit confused about the wording in the documentation for the ID life time of a fingerprint. It says several weeks but why would a fingerprint change even in this period of time?

- What device and browser are you using?
   Macbook Pro, google chrome

- What version of fingerprintjs are you using? 
   v3.3.3

**Comment by makma** [comment]
Hey @kanlancb,
A fingerprint issued by open-source FingerprintJS is calculated based on the current environment. The library collects signals from your environment and based on these pieces of data it calculates fingerprints. If something changes with your environment, the provided signal might change which results in the changed fingerprint. Please note, that I haven't used the term browser, I'd rather call it environment. You can e.g. buy a new screen, update the browser, update the operating system, update graphics card drivers, add an extension to the browser, etc. All these changes might cause a change in the entropy source (signal). That's the reason why the issued fingerprint may change.

**Comment by makma** [comment]
Marked as solved [here](https://discord.com/channels/852099967190433792/852100862134583336/973451751548133416).
