### ISSUE TITLE
Create a demo using React to further help beginners understand how to integrate fingerprintjs

### ISSUE THREAD

**Issue by kanlancb** [fingerprintjs/fingerprintjs#767]
Hello, 

As the title says, although experienced people can easily integrate fingerprintjs with their react applications, I think it would be better if we add demo's showing how fingerprint can be integrated with other popular frameworks like react, angular and such.

I can immediately make one demo with react and give it a pull request, while doing changes in the readme to integrate the new demo after approval.

Let me know your thoughts

**Comment by makma** [comment]
Hey @kanlancb! Thank you for this suggestion and initiative! I think this is a really good idea and it might be a useful project.

As far as I know (pls, correct me if I'm wrong Sergey) we don't want to include framework-specific code/examples in the main repository. Nevertheless, if you could prepare a separate example repository with documentation and demo, I assume we would link it from our readme. What do you think @Finesse?

**Comment by JsfasdF252** [comment]
[🧏‍♂️]()

**Comment by kanlancb** [comment]
@makma Any further thoughts on this?

**Comment by Finesse** [comment]
@makma I think that it doesn't make much sense to put effort into making and maintaining separate repository(s). I'd put code examples into the [docs](https://github.com/fingerprintjs/fingerprintjs/tree/master/docs) directory and maybe create interactive demos using StackBlitz (like it's done with the code examples in the readme). StackBlitz is a nice solution for small demos, and I think that the React demo code will fit into a single screen.

**Comment by makma** [comment]
Hello everyone!
I like the StackBlitz idea and the docs approach, what do you think @kanlancb?

**Comment by kanlancb** [comment]
Sounds good, let me do it from my personal account @kanlanc

**Comment by Finesse** [comment]
@makma Is there any progress on this issue? We should either add examples to the docs, or close the issue.

**Comment by kanlanc** [comment]
Hello, @Finesse  @makma , very for the delay will make a PR by this week tops

**Comment by Finesse** [comment]
@kanlanc What are you going to do in the PR?

**Comment by kanlanc** [comment]
@Finesse Add a react sandbox example and update the readme to reference the same

**Comment by kanlanc** [comment]
Hello @Finesse @makma ,

Here is the stackblitz url: https://react-ts-kxunqg.stackblitz.io

Please let me know if you want me to add or change something and meanwhile please let me know, the emails I will need to share the permissions to.

**Comment by kanlanc** [comment]
I will update the readme once I receive the go signal for the demo

**Comment by makma** [comment]
Hey @kanlanc,
The demo and code look good to me. For other folks, the original code can be found here: https://stackblitz.com/edit/react-ts-kxunqg?file=App.tsx.
@kanlanc feel free to add a readme with your handle or some other kind of attribution if you want. Also, please include the MIT license to the stackblitz project. Once you are done, share the link with me on this thread, I'll fork it and then I will provide you with a link for the readme. Sounds good?

**Comment by Finesse** [comment]
@kanlanc Any progress on this?

**Comment by kanlanc** [comment]
Yes, will do it this weekend, got caught up at work

**Comment by kanlanc** [comment]
@makma Sorry for the delay, freshly moved to New york so got caught up in that, I have added a readme with the handle, updated the package.json with the MIT license, please do let me know if there is anything else is required

**Comment by makma** [comment]
I added LICENSE file and proposed changes in https://github.com/fingerprintjs/fingerprintjs/pull/816
