### ISSUE TITLE
pro not working with AdBlock

### ISSUE THREAD

**Issue by ahmedyounes** [fingerprintjs/fingerprintjs#773]
Fingerprint js pro version is not working while there is adblock extension enabled , is there any way to overcome this extension ?
i didnt have this issue with fingerprintjs normal version .

**Comment by makma** [comment]
Hey @ahmedyounes,
Did you set up Subdomain integration correctly?

From docs:
Using a subdomain is required for correct identification while using FingerprintJS Pro.


src: https://dev.fingerprint.com/docs/subdomain-integration

**Comment by ahmedyounes** [comment]
@makma  thanks for the guide i will do it
