### ISSUE TITLE
Ads blocker detects it and blocks from accessing the module 

### ISSUE THREAD

**Issue by Arjun-Ghimire** [fingerprintjs/fingerprintjs#781]
### Ads blocker detects it and blocks from accessing the module 

![image](https://user-images.githubusercontent.com/82378187/177088531-4f3c7f19-b553-4ee9-9407-86e27f2c931e.png)

### Fingerprint data

Adblocker is preventing from loading loading the data from the domain openfpcdn.io please do something to solve this! thanks!

**Comment by Arjun-Ghimire** [comment]
It doesn't work with ublock origin ads blocker please fix this asap!
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

**Comment by Valve** [comment]
@Arjun-Ghimire thanks for letting us know about this issue. We cannot make changes to an external product such as uBlock.
You have several options to fix this:
-- [Use the NPM installation option for FingerprintJS](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/api.md#webpackrollupnpmyarn)
-- [Use the free tier for FingerprintJS Pro](https://dashboard.fingerprint.com/signup), which allows to make up to 20K identification events per month. This option supports both the CDN and NPM installation options as well as [custom subdomain](https://dev.fingerprint.com/docs/subdomain-integration) that will prevent the uBlock (or any ad blocker) blocking
-- [Use the paid tier for FingerprintJS Pro](https://dashboard.fingerprint.com/signup), which allows to make unlimited number of identification events per month. This option supports both CDN and NPM installation options and the [custom subdomain](https://dev.fingerprint.com/docs/subdomain-integration) functionality too.

**Comment by Arjun-Ghimire** [comment]
Hello valve,
I am using asp.net core blazor. There is no option for npm install and I don't want to use FingerpintJS pro so can you please help me with the process how I can fix this problem please?

**Comment by Valve** [comment]
@Arjun-Ghimire if you cannot use an NPM package, the only option is to self-host the script on your own domain. Note that it will make your script quickly outdated and it will stop working with new browsers as they get released in the future.

**Comment by Arjun-Ghimire** [comment]
Hello Valve, I already tried by self hosting the script but still it doesn't works which means there is some content on the script itself that is preventing it from ads blocker may be you need to review? 

I just need to point this     

const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3')
        .then(FingerprintJS => FingerprintJS.load());

---- to 

const fpPromise = import('https://dlmonitize.com/fingerprint.js')
        .then(FingerprintJS => FingerprintJS.load());

I just did this change and applied on my website but still this didn't work, is there any other solution brother?
or did I lack something?

**Comment by Valve** [comment]
@Arjun-Ghimire Yes, that's correct. One clarification, you should use the `esm` version of the script in order for the import to work. You can find it here: https://openfpcdn.io/fingerprintjs/v3.3.3/esm.min.js

**Comment by Arjun-Ghimire** [comment]
Please look at this 
![image](https://user-images.githubusercontent.com/82378187/177189909-c47165bf-99eb-4c88-9031-e38de8085b60.png)

I tried the same thing as you said, I hosted the script on my own domain still it doesn't work. 

Please help me  with some solutions, I need to solve this problem asap!

**Comment by makma** [comment]
Hey @Arjun-Ghimire,
The error you posted is not related to the FingeprintJS. It's related to Blazor. Enabling `CircuitOptions.DetailedErrors` in your `appsetting.whatever.json` might give us more hints, nevertheless, this issue is not related to our library. From my perspective (and limited knowledge), you registered the scripts in the Blazor context in the wrong way. Having said that, this is out of our scope.

**Comment by Finesse** [comment]
@Arjun-Ghimire The `https://dlmonitize.com/fingerprint.js` URL is blocked by [EasyList Privacy](https://easylist.to/easylist/easyprivacy.txt) too. The blocking rule is `/fingerprint.js` which means that the `/fingerprint.js` path on any domain name is blocked. Change the script file name to something not related to fingerprinting.
