### ISSUE TITLE
No, don't use it for fraud

### ISSUE THREAD

**Issue by kj7rrv** [fingerprintjs/fingerprintjs#792]
From the README:

> Fingerprint Pro is GDPR and CCPA compliant as the data processor. You still need to be compliant as the data controller and *use the identification for fraud* under legitimate interest or ask for user consent.

I don't think that's what it's supposed to say. It looks like it should say "use the identification for fraud prevention".

**Comment by Finesse** [comment]
@kj7rrv You are right, thank you

**Comment by makma** [comment]
Needs to be fixed also here: https://github.com/fingerprintjs/fingerprint.com/blob/0130b8a0466a393a6ef10f33d473356bf3192476/src/components/githubPage/FeatureComparisonSection/FeatureComparisonSection.tsx#L116
