### ISSUE TITLE
hashComponents doesn't exist for the pro version

### ISSUE THREAD

**Issue by ngohgia** [fingerprintjs/fingerprintjs#796]
### Scenario

- I want to extend the list of components as suggested here https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md . But it looks like the fingerjs-pro (v3.7.0) doesn't have the `hashComponents` function that the open-source version does (v3.3.4)
- Here's what the code looks like:
```
    const fpJsUrl = 'https://fpcdn.io/v3/<our-public-api-key>';
    let FpJS;
    const fpPromise = import(fpJsUrl)
      .then((FingerprintJS) => {
        FpJS = FingerprintJS;
        return FingerprintJS.load();
      });

    return fpPromise.then((fp) => fp.get())
      .then((result) => {
        const extendedComponents = {
          ...result.components,
          userId: { value: userId }
        };

        return FpJS.hashComponents(extendedComponents);
      })
      .catch((e) => {
        console.error(e)
      });
```

**Comment by makma** [comment]
Hey @ngohgia, that's correct. Fingerprint Pro does not have a custom extending functionality. Could you elaborate more on the use case?

From your code snippet, I can see you tried to add a `userId`. If you need to label your visitors with Pro, you can use [`linkedId`](https://dev.fingerprint.com/docs/js-agent#linkedid)s or [`tag`](https://dev.fingerprint.com/docs/js-agent#tag)s.
