### ISSUE TITLE
Unable to get city from fingerprintJS

### ISSUE THREAD

**Issue by himansh-gjr** [fingerprintjs/fingerprintjs#801]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
    - **Scenario**
        we are trying to get user's accurate location using FPJS
        
        ```javascript
        const fpPromise = FingerprintJS.load({
          apiKey: config.FINGER_PRINT_API_KEY,
        });

       fpPromise
          .then((fp) =>
            fp.get({
              extendedResult: true,
            })
          ).then((result) => {
            console.log(result); })
         ```
        
    - **what happens**
              In this result object, we are getting fields like latitude, longitude, continent and country inside" ipLocation"
               response from FingerprintJS :

        ```json
         {
              "requestId": "1660832546230.ZH2I4j",
              "browserName": "Chrome",
              "browserVersion": "104.0.0",
              "confidence": {
                  "score": 0.9971870604781997
              },
              "device": "Other",
              "firstSeenAt": {
                  "global": "2022-06-23T02:56:15.538Z",
                  "subscription": "2022-06-23T05:16:08.328Z"
              },
              "incognito": false,
              "ip": "103.171.98.50",
              "ipLocation": {
                  "accuracyRadius": 1000,
                  "continent": {
                      "code": "AS",
                      "name": "Asia"
                  },
                  "country": {
                      "code": "IN",
                      "name": "India"
                  },
                  "latitude": 21.9974,
                  "longitude": 79.0011,
                  "timezone": "Asia/Kolkata"
              },
              "lastSeenAt": {
                  "global": "2022-08-17T07:58:43.531Z",
                  "subscription": "2022-08-17T07:58:43.531Z"
              },
              "meta": {
                  "version": "v1.1.797+bc618187"
              },
              "os": "Mac OS X",
              "osVersion": "10.15.7",
              "visitorFound": true,
              "visitorId": "CRHEJRmtXDzbZRJHo2vR"
          }
        ```
        but city object is missing in these results ``` city: { "name": "Bengaluru" } ```
        I have checked on [FPJS DEMO](https://fingerprint.com/demo), there also it is giving the city object undefined.
        <img width="1392" alt="Screenshot 2022-08-18 at 7 06 26 PM" src="https://user-images.githubusercontent.com/77732259/185408557-65bf8379-9ea2-4322-a593-31d15d60df0f.png">

    - **expect to happen**
     city object should be present in the "ipLocation" object in results
    Unexpectedly for some cases, it gives the city object but not every time ( not able to figure out the exact case, when it provides and when it does't provide the city  ) 

- What device and browser are you using?
  - Device: MacBook Air (M1, 2020), macOS monterey V:12.2.1 
  - Browser: Google Chrome, Version 104.0.5112.79 (Official Build) (arm64)

- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment.)
we are using Free Plan of FingerprintJS
version : "@fingerprintjs/fingerprintjs-pro": 3.5.6

**Comment by Valve** [comment]
@himansh-gjr can you please try again our demo and let us know if it correctly showed the city name?

**Comment by himansh-gjr** [comment]
@Valve yeahh! It is working well now, thanks.

**Comment by Valve** [comment]
@himansh-gjr I'm closing this PR since you said it's now working for you. Please feel free to reopen if something new comes up.

**Comment by himansh-gjr** [comment]
Hii @Valve , It's great that the issue has been resolved but I am curious to know more about the issue.
It would be great if you can share
1. why does the issue occur? 
2. how did you guys fix the issue?

**Comment by Valve** [comment]
@himansh-gjr this issue existed because we used an older version of the API the we use to geolocate the IP addresses.
Once we upgraded to the latest version, it started working.

**Comment by seancsy** [comment]
You can try whoer and ipdog.io, which can detect ip and browser fingerprint information
