### ISSUE TITLE
Nodejs server render will make 'atob is not defined'.

### ISSUE THREAD

**Issue by dupeiduo** [fingerprintjs/fingerprintjs#806]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
- What device and browser are you using?
- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment.)

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by Finesse** [comment]
This is fixed by https://github.com/fingerprintjs/fingerprintjs/pull/805 and will be published in the next release.

For now please update Node.js to version 16 (it supports `atob`) or add an `atob` polyfill/stub to your application.
