### ISSUE TITLE
`cookiesEnabled` returns `false` when runs in a cross-origin iframe

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/fingerprintjs#807]
### Scenario

- What causes the fingerprint to change?
>iframe
- What device and browser are you using?
>MacBook Air (M2) with macOS 12.5, Chrome 104.0.5112.101 (arm64)
- What version of FingerprintJS are you using? 
>FingerprintJS v3.3.5

### Step to reproduce
1. create two local site named `finger1.test` and `finger2.test` with following code (note that in `finger2.test` has an iframe of `finger1.test`):
```
➜  cat finger1.test/index.html
<script>
  // Initialize the agent at application startup.
  const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3')
    .then(FingerprintJS => FingerprintJS.load())

  // Get the visitor identifier when you need it.
  fpPromise
    .then(fp => fp.get())
    .then(result => {
      // This is the visitor identifier:
      const visitorId = result.visitorId
      console.log('finger1 id: ' +visitorId)
    })
</script>
```
```
➜  cat finger2.test/index.html
<iframe src="https://finger1.test/index.html"></iframe>
<script>
  // Initialize the agent at application startup.
  const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3')
    .then(FingerprintJS => FingerprintJS.load())

  // Get the visitor identifier when you need it.
  fpPromise
    .then(fp => fp.get())
    .then(result => {
      // This is the visitor identifier:
      const visitorId = result.visitorId
      console.log('finger2 id: ' + visitorId)
    })
</script>
```
2. then visit `finger2.test`, you will see two different visitorIds in the console:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4530539/187011963-856c6585-1410-4010-8d28-85da03d1fcc9.png">

**Comment by Finesse** [comment]
Hello @tvvocold. What is the iframe URL on your screenshot? Please provide the fingerprint components:
```js
// Initialize the agent at application startup.
const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3')
  .then(FingerprintJS => FingerprintJS.load())

// Get the visitor identifier when you need it.
fpPromise
  .then(fp => fp.get())
  .then(result => {
    // This is the visitor identifier:
    const visitorId = result.visitorId
    console.log(`Components: ${JSON.stringify(result.components, null, 2)}`)
  })
```

**Comment by tvvocold** [comment]
hi @Finesse, 
the iframe is `finger1' html, you can easily reproduce this bug by creating two simple local site as I paste here ( including the components ) : https://gist.github.com/tvvocold/93060a46bb4392d62ea37e1fcca515f4

**Comment by Finesse** [comment]
Thank you! I was able to identify the issue: the [`cookiesEnabled` entropy source](https://github.com/fingerprintjs/fingerprintjs/blob/master/src/sources/cookies_enabled.ts) gives `false` when FingerprintJS runs in a cross-origin iframe in Blink. When a single entropy component changes, the whole fingerprint changes. I'll check what we can do to stabilize it.

For now you can exclude the entropy component by following the [extending guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md).

**Comment by Finesse** [comment]
I've tried this solution:
```js
export default function areCookiesEnabled() {
  const cookieName = 'cookietest='
  const cookieInits = [
    `${cookieName}1; SameSite=None; Secure`, // I've added this
    `${cookieName}1; SameSite=Strict`
  ]

  for (const cookieInit of cookieInits) {
    try {
      d.cookie = cookieInit
      const result = d.cookie.indexOf(cookieName) > -1
      d.cookie = `${cookieInit}; expires=Thu, 01-Jan-1970 00:00:01 GMT`
      if (result) {
        return true
      }
    } catch {}
  }

  return false
}
```

This is the result (the behavior of `areCookiesEnabled()` in a cross-origin iframe):

| | Regular mode | Incognito mode |
|---------|----------|--------|
| Chrome 104 | Fixed | The result is `false` regardless. `navigator.cookiesEnabled` is `false`, i.e. cookies are disabled completely |
| Safari 16 | The result is `false` regardless. `navigator.cookiesEnabled` is `false`, i.e. cookies are disabled completely | ← Same |
| Firefox 103 | Fixed | Fixed |

The table shows that the fix above makes FingerprintJS produce different result in regular and incognito modes in Chrome in case of a cross-origin iframe. Generating the save fingerprint in root and framed pages is not a necessary feature of FingerprintJS. Having a consistent result in regular/incognito modes is much more important.

If you have to get fingerprints in iframes, then you can fix the issue on your side by generating fingerprints only in cross-origin iframes. It will be even more reliable than excluding the `cookiesEnabled` entropy source.

Thus I'm closing the issue as "won't fix". If you have more information or know how to stabilize the entropy source, feel free to reopen the issue.

**Comment by tvvocold** [comment]
Hi @Finesse,
Thx for the answer, I try to exclude the `cookiesEnabled` entropy component, but it didn't work. The code is here:
https://gist.github.com/tvvocold/ef177ab2cc93eefc5d3b0104cc6a26ee 
Am I missing something here?

**Comment by tvvocold** [comment]
@Finesse Just found another issue with iframes, in Safari 15.6 (17613.3.9.1.5), the `vendorFlavors` is empty in iframes.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/4530539/187054158-602c9212-83b5-44a6-b2d0-dd8be8caf7c4.png">

Here is my testing code: 
> ```
>   const fpPromise = FingerprintJS.load();
> 
>   (async () => {
>     const fp = await fpPromise;
>     const result = await fp.get();
>     const { cookiesEnabled, ...components } = result.components;
>     const visitorId = FingerprintJS.hashComponents({...components});
>     console.log(visitorId);
>   })();
> ```

**Comment by Finesse** [comment]
@tvvocold The situation is the same. If we exclude the `vendorFlavors` component, the library will lose some of the sensitivity. If you need a stable result, use FingerprintJS in a single environment (cross-origin iframes in your case).

**Comment by tvvocold** [comment]
hi @Finesse, 
Sorry to bother you again, just wanna know how to exclude the component in Promise like [the Readme's demo code](https://github.com/fingerprintjs/fingerprintjs#quick-start) , I'm trying the following code but it's not working,  an error said that `Uncaught (in promise) ReferenceError: FingerprintJS is not defined` with this line `FingerprintJS.hashComponents({ ...components })`

```
const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3 ')
    .then(FingerprintJS => FingerprintJS.load())

// Initialize an agent at application startup.
fpPromise
    .then(fp => fp.get())
    .then(result => {
        const { cookiesEnabled, plugins, screenFrame, vendorFlavors, ...components } = result.components;
        const visitorId = FingerprintJS.hashComponents({ ...components });  // an error in this line "Uncaught (in promise) ReferenceError: FingerprintJS is not defined"
        console.log(visitorId)
    })
```

**Comment by Finesse** [comment]
@tvvocold Yes, this is correct
