### ISSUE TITLE
Unstable 'plugins' entropy source in Chrome incognito/private mode

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/fingerprintjs#808]
### Scenario

- What causes the fingerprint to change?
>the `plugins` entropy source changed in Chrome incognito/private mode
- What device and browser are you using?
>MacBook Air (M2) with macOS 12.5, Chrome 104.0.5112.101 (arm64)
- What version of FingerprintJS are you using? 
>FingerprintJS v3.3.5

### Fingerprint data
> the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/

Pasted here: https://www.diffchecker.com/BJrdUafl

**Comment by Finesse** [comment]
Can you reproduce this is a stable way? If yes, please share the steps.

This looks similar to https://github.com/fingerprintjs/fingerprintjs/issues/794

**Comment by tvvocold** [comment]
I can't, just tested it again, it is back to normal with two same ids, so weird.

> Can you reproduce this is a stable way? If yes, please share the steps.
> 
> This looks similar to #794

**Comment by Finesse** [comment]
We know that the entropy component is slightly unstable in Chrome. You can read more about it (with proposed solutions) at #794. We will probably replace it with [navigator.pdfViewerEnabled](https://github.com/fingerprintjs/fingerprintjs/pull/795) in v3.4.0. So I'm closing the issue.
