### ISSUE TITLE
NotSupportError - The operation is not supported in Safari on IOS 16

### ISSUE THREAD

**Issue by chuotnhat1985** [fingerprintjs/fingerprintjs#823]
### Scenario

- It is happened DOM Exception: NotSupportError - The operation is not supported in Safari on IOS 16
- Iphone with IOS 16 on Safari
- FingerprintJS v3.3.6

### Fingerprint Data
Mozilla/5.0 (iPhone; CPU iPhone OS 16_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1

**Comment by Finesse** [comment]
Hello @chuotnhat1985. Thank you for reporting this. Unfortunately, I can't reproduce this. Could you please provide more details:

- Steps to reproduce
- The page URL
- What's the exact output (is the error thrown or it is a prat of the regular result)
- The stack trace (where exactly the code the error occurs)

**Comment by chuotnhat1985** [comment]
Hi @Finesse. Thanks for your response. I just call loadSources and get the error as the screenshot.
`const fpPromise = loadSources(sources, {}, [
    "screenResolution",
    "screenFrame",
    "canvas",
    "fontPreferences",
    "languages",
  ])();`
[url=https://ibb.co/TBTNCQ9][img]https://i.ibb.co/ccvsmW4/2022-10-25-16-12-03-itnw-s-Mac-mini-Tight-VNC-Viewer.png[/img][/url]

**Comment by Finesse** [comment]
@chuotnhat1985 

- What does `fpPromise` resolve to or throws?
- What's the page full URL? (even if it's a local address)
- Please provide an HTML file that I can reproduce the error with
- Are there any important settings on your iPhone such as Lockdown Mode?

**Comment by Finesse** [comment]
Closing because of the lack of response and not hearing about this problem anymore. Feel free to comment if you have additional information, I'll reopen the issue.
