### ISSUE TITLE
iOS 16 Safari private mode returns false for incognito

### ISSUE THREAD

**Issue by ratnev** [fingerprintjs/fingerprintjs#824]
iOS 16 Safari private mode returns false for incognito while .get method. It works for Safari on Mac OS, chrome mobile and desktop as well.

*Scenario*

- open request url in private mode in safari iOS mobile 
- check if incognito mode in fingerprint object exist (true) while .get method

*Fingerprint Data*

Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1

**Comment by Valve** [comment]
@ratnev sorry for the late reply, I just tried it but was unable to reproduce it. Can you reproduce it on our website home page?

**Comment by ratnev** [comment]
@Valve I've tried to open the https://fingerprint.com/demo/ on Mobile Safari on IOS (in private mode) and it does states "YES" for "INCOGNITO".

But it's not my case. The problem is that the same code I use, returns different values for "incognito" on different iOS versions on Mobile Safari. Everything works as expected if iOS version (major) <= 15, otherwise it returns incognito: false only on Mobile Safari on iOS.

**Comment by ratnev** [comment]
Opened a Safari page in Private mode through localtunnel (iPhone 14 Pro, locally) and inspected the page via Safari dev tools on Mac OS.

The response I get from fingerprint (standard get method):

{
    browserName: "Mobile Safari",
    browserVersion: "16.1",
    device: "iPhone",
    incognito: false,
    ip: "176.100.6.61",
    os: "iOS",
    osVersion: "16.1",
    visitorId: "zA4XJnVccnO3AwM8Ya5y"
}

**Comment by Finesse** [comment]
@ratnev Please share a couple of `requestId` values that you got in cases when the `incognito` value was incorrect

**Comment by Valve** [comment]
@ratnev thanks for providing all the additional details, please upgrade to the latest version of the JS agent and let us know if the situation persists.
