### ISSUE TITLE
How is it used in Chrome Extensions with manifest V3?

### ISSUE THREAD

**Issue by nicolaswww** [fingerprintjs/fingerprintjs#855]
### Scenario

- We were using `@fingerprintjs/fingerprintjs-pro` in our chrome extension and didn't experience any issues with the chrome manifest V2.
As of January 2023, chrome requires that manifest v3 be used and one of the restrictions is the impossibility of loading external JS files (as requested by fingerprint in the documentation). This impossibility is because in mv3, chrome limits the possible values of the content_security_policy: [Chrome Documentation](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#content-security-policy).
Is it possible to use fingerprintjs without the need to import a JS dynamically? An important fact, our apiKey is dynamic.

- Device: Browser - Chrome

- Version: @fingerprintjs/fingerprintjs-pro 3.7.1

### Fingerprint data

Visitor identifier: `4c92206b6c3bc6d96d2068fd3b615018`
Time took to get the identifier: 366ms
Confidence: {"score":0.5,"comment":"0.995 if upgrade to Pro: https://fpjs.dev/pro"}
User agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

**Comment by Finesse** [comment]
Hi @nicolaswww. This guide should help in your case: https://dev.fingerprint.com/docs/fingerprintjs-pro-and-chrome-extension

**Comment by nicolaswww** [comment]
> Hi @nicolaswww. This guide should help in your case: https://dev.fingerprint.com/docs/fingerprintjs-pro-and-chrome-extension

The iframe approach worked with mv3, thanks!
