### ISSUE TITLE
TIMEZONE

### ISSUE THREAD

**Issue by DrPerkyLegit** [fingerprintjs/fingerprintjs#857]
### Scenario

- What causes the fingerprint to change?
- timezone
- What device and browser are you using?
- ios, apples built in webkit
- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment)
- free / public version

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

change timezone on ios and your fingerprint will not be the same

**Comment by Finesse** [comment]
Hello @DrPerkyLegit. Fingerprinting technology is based not only on device traits, but also on user preferences which give much entropy. It's expected for fingerprint to change when the selected user settings change. Timezone is one of them. So, we don't consider it as a problem.

If it's a problem for you, you can [exclude](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) the timezone component from your fingerprint. Such way you'll decrease the chance of assigning different fingerprints to the same user but also decrease the number of users that you can distinguish from each other.

Fingerprinting is not a 100% accurate technology. We have to choose a balance between stability and sensitivity (which I described in the previous paragraph). Also consider trying [Fingerprint Pro](https://fingerprint.com/github) to improve the accuracy of your fingerprint; it uses techniques that are impossible to use on client side (FingerprintJS Open-Source is fully client-side).
