### ISSUE TITLE
InstallTrigger should no longer be used and will be removed in the future.

### ISSUE THREAD

**Issue by merlincom** [fingerprintjs/fingerprintjs#858]
Version 3
const fpPromise = import('https://fpjscdn.net/v3/key')
 
Warnung in Firefox-Konsole: 
InstallTrigger sollte nicht mehr verwendet werden und wird in Zukunft entfernt.
InstallTrigger should no longer be used and will be removed in the future.

**Comment by Finesse** [comment]
This is a known problem and will be fixed soon.

I’m closing this because it is related to Fingerprint Pro, not FingerprintJS.

**Comment by merlincom** [comment]
Thank you for helping and have a good time.
