### ISSUE TITLE
Content Security Policy Issue in next js example repo

### ISSUE THREAD

**Issue by jimsheen** [fingerprintjs/fingerprintjs#863]
Hi there, I have been trying to implement the react fingerprint js npm package into my next js project and come up against CSP issues blocking requests to your servers.

I just cloned your next js example package and can confirm the same CSP issues occur here. Please could you help me understand how I can work around this please? 

I have tried to update the CSP in the `next.config.js` based on these docs but still the requests are being blocked:
https://nextjs.org/docs/advanced-features/security-headers 
https://dev.fingerprint.com/docs/js-agent-csp

Any help resolving this issue would be greatly appreciated. Please let me know if I can provide any further information

![image](https://user-images.githubusercontent.com/3286804/212570604-ad339fe7-de33-49a7-9fea-f7a47f6c859d.png)

```
// next.config.js

/** @type {import('next').NextConfig} */


const ContentSecurityPolicy = `
	base-uri 'self';
	default-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.fptls.com https://*.fptls2.com https://eu.api.fpjs.io https://fpnpmcdn.net;
	style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
`;

const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: ContentSecurityPolicy.replace(/\s{2,}/g, ' ').trim(),
  },
];


const nextConfig = {
  reactStrictMode: true,
	async headers() {
		return [
			{
				source: '/(.*)',
				headers: securityHeaders,
			},
		]
	}
}

module.exports = nextConfig

```

**Comment by JuroUhlar** [comment]
Hello @jimsheen, thanks for reaching out!

Is it possible that Adblock, uBlock, or a similar extension in your browser is blocking the requests?  Have you tried running the page in a browser without extensions? 

Our Next.js example does not contain any CSP headers by default. During my tests, whenever Fingerprint was blocked by CSP, I would get a CSP-specific error in the console such as: `Content Security Policy: The page’s settings blocked the loading of a resource at https://fpjscdn.net/v3/2UZgp3skqLzfJpFUGUrw (“default-src”)`. 

On the other hand, requests blocked by ad-blockers often result in a generic `ERR_BLOCKED_BY_CLIENT` error.

**Comment by jimsheen** [comment]
@JuroUhlar Thanks for the swift reply. I was using Brave browser for local development, tried to run the example project in chrome and disabled adblock but still getting the same issue. However, it did work in Firefox so at least I have a way to test the implementation in my local environment.

When it comes to deployment I will look into routing through a sub domain as you mentioned - many thanks for the helpful reply and links!

**Comment by Finesse** [comment]
@jimsheen Please double-check you Chrome extensions. Bare Chrome doesn't block Fingerprint Pro requests. The quickest way to disable all extensions is going into Incognito mode.
