### ISSUE TITLE
How to get the city, ip and other information in fingerprntpro, how to write the code

### ISSUE THREAD

**Issue by mangic** [fingerprintjs/fingerprintjs#873]

**Comment by JuroUhlar** [comment]
Hello @mangic! 

You can use the `extendedResult` property in the `get` parameter object to reveal IP and location information in the Fingerprint Pro response. 

```js
const fpPromise = import('https://fpjscdn.net/v3/your-public-api-key')
  .then(FingerprintJS => FingerprintJS.load())

fpPromise
  .then(fp => fp.get({ extendedResult: true }))
  .then(result => console.log(result.ip, result.ipLocation)) 
```

You can find more information in our [documentation](https://dev.fingerprint.com/suggested-edits/63f3663f9386e3058718b845/preview). 
You can also explore full use case examples in the  [Fingerprint Pro Use Cases](https://github.com/fingerprintjs/fingerprintjs-pro-use-cases) repository.

**Comment by Finesse** [comment]
I'm closing this because it's about Fingerprint Pro, not FingerprintJS
