### ISSUE TITLE
Firefox with resistFingerprinting on gives different fingerprints every time with FingerprintJS Pro

### ISSUE THREAD

**Issue by chuanhhoang** [fingerprintjs/fingerprintjs#882]
### Scenario

- What causes the fingerprint to change? resistFingerprinting on
- What device and browser are you using? Firefox
- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment): https://fingerprint.com/demo/

So basically turning on resistFingerprinting breaks FingerprintJS.

**Comment by makma** [comment]
Hey @chuanhhoang, thanks for reaching out. Fingerprint Pro does not provide this feature right now. In general, for product-related questions, we recommend reaching out to [support@fingerprint.com](mailto:support@fingerprint.com) or submitting your idea to our product team directly via our [product board](https://portal.productboard.com/fingerprintjs/1-fingerprint-product-roadmap/tabs/1-under-consideration.).
