### ISSUE TITLE
Remove WebSQL usage and/or method calls from this repository

### ISSUE THREAD

**Issue by ccsmith13** [fingerprintjs/fingerprintjs#884]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
**Web SQL is on its way out and is being slowly <a href=”https://developer.chrome.com/blog/deprecating-web-sql/#web-sql-deprecation-and-removal-steps”>deprecated</a>. Web SQL access in insecure contexts is deprecated as of Chromium 105 and a warning message is shown in the Chrome DevTools Issue panel. It's planned to fully remove it in later versions. Currently fingerprintjs still enables the feature by making calls to WebSQL's `openDatabase` method (https://github.com/search?q=repo%3Afingerprintjs%2Ffingerprintjs+openDatabase&type=code)**
- What device and browser are you using? **Any, Chrome**
- What version of FingerprintJS are you using? **Current version**

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

N/A

**Comment by Finesse** [comment]
Hello @ccsmith13. This issue doesn't affect the performance or accuracy, so it is not important. WebSQL was disabled in insecure contexts in Chrome 110, so the message doesn't appear anymore. Because this issue is not important and affects only a small portion of Chrome versions, it is not worth fixing it.

**Comment by Finesse** [comment]
Also if we stop using `window.openDatabase`, many visitor identifiers will change. There should be a good reason to do such change.
