### ISSUE TITLE
Getting net::ERR_BLOCKED_BY_CLIENT with Adblocker extension

### ISSUE THREAD

**Issue by RambabuPatina** [fingerprintjs/fingerprintjs#915]
### Scenario
When loading the script https://fpnpmcdn.net/v3/wXWhGQGXg9383RclZUdq/loader_v3.8.1.js in HTML file facing below issue when adblocker extension has been installed in the browser. When disable/allow always addblocker in the page it loads the script successfully.
```
GET https://fpnpmcdn.net/v3/wXWhGQGXg9383RclZUdq/loader_v3.8.1.js net::ERR_BLOCKED_BY_CLIENT
```

I am on MacOs and Chrome latest version.
Consuming @fingerprintjs/fingerprintjs-pro@3.8.1 version in our app.

Please fix it ASAP as it's impacting our customers. If any workaround let us know. Thanks

**Comment by makma** [comment]
Hello, please read [Protecting the JavaScript agent from ad blockers](https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers) where we explain how to circumvent this issue.
