### ISSUE TITLE
How to get the city, ip and other information in fingerprntjs v4, how to write the code

### ISSUE THREAD

**Issue by mangic** [fingerprintjs/fingerprintjs#930]
const fpPromise = import('https://openfpcdn.io/fingerprintjs/v4')
.then(FingerprintJS => FingerprintJS.load())
const getVisitorIdPromise = new Promise((resolve, reject) => {
fpPromise
.then(fp => fp.get({ extendedResult: true }))
.then(result => {
visitorId = result.visitorId;
resolve(visitorId);
.............
})
.catch(error => {
});
});

**Comment by JuroUhlar** [comment]
Hello @mangic, 

FingerprintJS does not use or provide IP-based location as one of its fingerprinting parameters. If you need use geolocation, consider upgrading to [Fingerprint Pro](https://fingerprint.com/github/).

**Comment by mangic** [comment]
@JuroUhlar hi
Can you help me find out why the following code cannot be used when switching to the v4 version?

let fingerprint;
const fpPromise = import("https://openfpcdn.io/fingerprintjs/v4").then(
  (FingerprintJS) => {
    fingerprint = FingerprintJS
    return FingerprintJS.load()
  }
);

fpPromise
  .then((fp) => fp.get())
  .then((result) => {
    const { languages, audio } = result.components;
    const visitorId = fingerprint.hashComponents(languages, audio);
    console.log(visitorId);
});
