### ISSUE TITLE
I'm not sure if FingerprintJS V4 excludes the component according to the code I wrote.

### ISSUE THREAD

**Issue by mangic** [fingerprintjs/fingerprintjs#938]
is this correct?👇

`let fingerprint;
const fpPromise = import("https://openfpcdn.io/fingerprintjs/v4").then(
  (FingerprintJS) => {
    fingerprint = FingerprintJS
    return FingerprintJS.load()
  }
);

fpPromise
  .then((fp) => fp.get())
  .then((result) => {
    const { languages, audio, canvas, screenResolution } = result.components;
    const visitorId = fingerprint.hashComponents(result.components);
});`

**Comment by bragle** [comment]
If you are trying to exclude `languages`, `audio`, `canvas` and `screenResolution` from affecting your hash, then no. Destructuring an object will not affect the object itself (you can read more [here](https://javascript.info/destructuring-assignment)). I'd recommend doing a javascript tutorial like [this](https://javascript.info/). What I'm guessing you're trying to do is something like this:

```js
const { languages, audio, canvas, screenResolution, ...remainingComponents } = result.components;

const visitorId = fingerprint.hashComponents(remainingComponents)
```

This uses the spread syntax to get the remaining items when destructuring the object (you can read more [here](https://javascript.info/rest-parameters-spread)).

**Comment by mangic** [comment]
yes,i want exclude languages,audio,canvas but i failed

**Comment by mangic** [comment]
@bragle thanks
