### ISSUE TITLE
有时候为什么会报这个错?

### ISSUE THREAD

**Issue by plusby** [fingerprintjs/fingerprintjs#966]
![image](https://github.com/fingerprintjs/fingerprintjs/assets/28599723/4b75805f-629d-41c8-8ae5-df942f782581)

**Comment by JuroUhlar** [comment]
Hi @plusby I am not sure I understand your question. Have you encountered this error while running FingerprintJS? Can you please provide more context or a minimal reproduction example? Thanks a lot!

**Comment by JuroUhlar** [comment]
Closing due to insufficient information for now.
