### ISSUE TITLE
Empty Notification 4.2.0

### ISSUE THREAD

**Issue by GNURub** [fingerprintjs/fingerprintjs#968]
With this change [change](https://github.com/fingerprintjs/fingerprintjs/commit/349d56e2ba315338bf12594f863e81d2c3ac5f20#diff-e5eaf8000fb66db2f8c2de24db5df7b6f2b9b058c2a3a119239f8d39673ea79aR301) now it is throwing an empty notification every time the page loads.

**Comment by Finesse** [comment]
Thanks for reporting. We are working on this.

How to reproduce:

1. Open https://fingerprintjs.github.io/fingerprintjs/ in Chrome
2. Allow notifications in the Site settings
3. Reload the page
