### ISSUE TITLE
same visitor id on two different device in iphone 13 

### ISSUE THREAD

**Issue by chandreshGSCT** [fingerprintjs/fingerprintjs#972]
i have get visitor id but issue was in my iphone and my friend iphone are getting same visitor id

my code is here 

   // My code
export class HardwareSerialNumberService {
  async getSerialNumber(): Promise<string> {
    try {
      const fp = await Fingerprint.load();
      // The FingerprintJS agent is ready.
      // Get a visitor identifier when you'd like to.
      const result = await fp.get();

      // This is the visitor identifier:
      const visitorId = result.visitorId;
      return visitorId;
    } catch (error) {
      console.error('Error getting fingerprint:', error);
      throw error;
    }
  }
}

**Comment by JuroUhlar** [comment]
Hi @chandreshGSCT, thanks for the report, could you provide us with the visitor ID? We will investigate what happened, thank you!

**Comment by chandreshGSCT** [comment]
here is my fingerprint "81ff4856e4822e81c8e3ff43c3869052"

i have used in chrome and my mobile model iPhone 13, 128GB updated OS and Browser Version (Both device is same)

**Comment by JuroUhlar** [comment]
Answered in the duplicate discussion here: https://github.com/fingerprintjs/fingerprintjs/discussions/971#discussioncomment-7690827
