### ISSUE TITLE
GDPR compliance: Provide instructions on how to clear stored state of the pro version

### ISSUE THREAD

**Issue by bugreporter321** [fingerprintjs/fingerprintjs#973]
### Scenario

The pro version is seemingly writing an undeletable identifier into the safari browser.
This is in contradiction to the GDPR. Cookies need measure of deletion even if you encode them with technically different storage.

The only current approach is a device reset. This is not acceptable.

Please provide instructions how to remove the supercookie.

**Comment by Valve** [comment]
Hi @bugreporter321 
To be able to help you, can you please provide additional information:

1. The name and type of the identifier you're having troubles deleting. Once we know which identifier you refer to, we'll help you delete it.
2. Can you please link to the GDPR part that doesn't allow storing identifiers of this type? I'd be curious to learn more about this.

**Comment by bugreporter321** [comment]
Maybe my observation is not correct in which case please accept my apology; yet could you shed some light on why in case of ios a device reset would alter the visitorID technically? The system software should not change on a reset, and the open source fingerprint does not change either. Unless on ios certain obvious system properties accessible to javascript are randomized on device initialization, I fail to understand what else except state encoded in favicon, tls session resumption, or similar could cause this behaviour? As the cookies can be and are cleared in safaris private mode, these are out of the game as easy explanation. While I understand you have to keep your business secrets, could you give a hint about the things you store in a browser state with regard to GDPR? Thanks

**Comment by Valve** [comment]
It's possible that some properties change during the factory reset and that may cause the identifier to change. 
If you need more information about why it changed in your particular case, please contact support@fingerprint.com with your account and the visitorID before and after and we'll help you.
Regarding browser storage, Fingerprint Pro JavaScript agent can store a random string in cookies and local storage. 
Hope this answers your question. I'm closing this ticket as not related to FingerprintJS (the library).

**Comment by bugreporter321** [comment]
For example:OdWF8PxpgCVSjjuiO4z1OdWF8PxpgCVSjjuiO4z1Vsx97ymIYFwxFQnc2fZ8KnVsoIkPTnhEsP0vDGXFcN2JWhat might be the difference between these?ThanksAm 28.11.23 um 19:55 schrieb Valve
                
            
            
                
                    Von: "Valve" ***@***.***>Datum: 28. November 2023An: "fingerprintjs/fingerprintjs" ***@***.***>Cc: "Mention" ***@***.***>,"bugreporter321" ***@***.***>Betreff: Re: [fingerprintjs/fingerprintjs] GDPR compliance: Provide instructions on how to clear stored state of the pro version (Issue #973)
                
                
It's possible that some properties change during the factory reset and that may cause the identifier to change.
If you need more information about why it changed in your particular case, please contact ***@***.*** with your account and the visitorID before and after and we'll help you.
Regarding browser storage, Fingerprint Pro JavaScript agent can store a random string in cookies and local storage.
Hope this answers your question. I'm closing this ticket as not related to FingerprintJS (the library).
