### ISSUE TITLE
CORS errros when accessing openfpcdn.io from Firefox

### ISSUE THREAD

**Issue by jcubic** [fingerprintjs/fingerprintjs#976]
### Scenario

The demo doesn't work in Firefox. It gives CORS errors from openfpcdn.io.

This is my old CodePen demo, just tested it in Firefox. In works in Chrome:

https://codepen.io/jcubic/pen/YzYzjqw?editors=1111

The same happens with the latest demo from README.

This works fine:
https://fingerprintjs.github.io/fingerprintjs/

I use uBlock but allowed the code from openfpcdn.io domain

### Fingerprint data

The issue is not with fingerprint

**Comment by Valve** [comment]
Hi @jcubic 
Firefox blocks this CDN domain. 
Please use the NPM package.
I'm closing this issue, feel free to reopen with additional information.

**Comment by pilotkid** [comment]
Is there an alternate CDN that is 1st party supported?
