### ISSUE TITLE
An error will be reported in IE8/9/10 because they do not have navigator.vendor

### ISSUE THREAD

**Issue by 941477276** [fingerprintjs/fingerprintjs#977]
### Scenario

- What's the scenario, what happens and what did you expect to happen?
- Running the code in IE8/9/10 will give a TypeError: could not get undefined or null reference to the property "indexOf". I checked and found that the problem is caused by accessing `navigator. vendor` in the `isChromium` and `isWebKit` functions, because the value of `navigator. vendor` in IE8/9/10 is `undefined`.
- 
![image](https://github.com/fingerprintjs/fingerprintjs/assets/20528541/fd52ca2d-5920-435b-88ef-9bf05fba1fdd)
![image](https://github.com/fingerprintjs/fingerprintjs/assets/20528541/5834cb3f-0289-40ae-b85f-686f6014abdf)

- What device and browser are you using?
- IE8/9/10
- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment.)
- 4.2.1

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.
```
 /**
     * Checks whether the browser is based on Chromium without using user-agent.
     *
     * Warning for package users:
     * This function is out of Semantic Versioning, i.e. can change unexpectedly. Usage is at your own risk.
     */
    function isChromium() {
        // Based on research in October 2020. Tested to detect Chromium 42-86.
        var w = window;
        var n = navigator;
        return (countTruthy([
            'webkitPersistentStorage' in n,
            'webkitTemporaryStorage' in n,
            n.vendor.indexOf('Google') === 0,
            'webkitResolveLocalFileSystemURL' in w,
            'BatteryManager' in w,
            'webkitMediaStream' in w,
            'webkitSpeechGrammar' in w,
        ]) >= 5);
    }
    /**
     * Checks whether the browser is based on mobile or desktop Safari without using user-agent.
     * All iOS browsers use WebKit (the Safari engine).
     *
     * Warning for package users:
     * This function is out of Semantic Versioning, i.e. can change unexpectedly. Usage is at your own risk.
     */
    function isWebKit() {
        // Based on research in September 2020
        var w = window;
        var n = navigator;
        return (countTruthy([
            'ApplePayError' in w,
            'CSSPrimitiveValue' in w,
            'Counter' in w,
            n.vendor.indexOf('Apple') === 0,
            'getStorageUpdates' in n,
            'WebKitMediaKeys' in w,
        ]) >= 4);
    }
```

**Comment by Finesse** [comment]
Internet Explorer is not supported. You can find the list of supported browsers [here](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/browser_support.md). If you need to support old versions of IE, consider using an old FingerprintJS version (v2 or older).
