### ISSUE TITLE
deviceid changed in mac os

### ISSUE THREAD

**Issue by cndnhere** [fingerprintjs/fingerprintjs#987]
The issue is in Mac OS, the device ID changes if I open the browser the next day.

**Comment by JuroUhlar** [comment]
Hi @cndnhere, would you mind posting a full JSON from https://fingerprintjs.github.io/fingerprintjs/ before and after the browser restart? It will help us pinpoint exactly which browser you are using, which entropy components have changed and we will take it from there. Thanks a lot!

**Comment by asif-jalil** [comment]
@JuroUhlar same issue happend to me. This problem was happened for mac OS full screen mode. I found this problem happened for screen frame. 

When i am in the full screen mode, 

```
"screenFrame": {
    "value": [
      0,
      0,
      0,
      0
    ],
    "duration": 0
  },
```

And when i am not in the full screen mode,

```
"screenFrame": {
    "value": [
      30,
      0,
      60,
      0
    ],
    "duration": 1
  },
```

**Comment by JuroUhlar** [comment]
Thanks for the info! @Finesse is this a known limitation?

**Comment by JuroUhlar** [comment]
I have confirmed it is a known limitation of FingerprintJS that entering fullscreen mode will cause a false negative in certain browser/OS combinations, you can read more details here: https://github.com/fingerprintjs/fingerprintjs/issues/568 

If this is a problem for your use case, you can [exclude](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) `screenFrame` from the entropy components.  Or you can switch to [Fingerprint Pro](https://fingerprint.com/github/), which handles this type of small signal changes and returns the same stable visitor ID.

**Comment by JuroUhlar** [comment]
Closing the issue for now, feel free to open if you have more questions.
